### ISSUE TITLE
Add expand arrow for description view

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/prox#106]
The description views are supposed to have an arrow.
![screen shot 2016-11-04 at 16 29 18](https://cloud.githubusercontent.com/assets/759372/20025474/e3603028-a2ab-11e6-81fd-bf04b2fa8b97.png)

**Comment by mcomella** [comment]
It's supposed to flip up when expanded:
![screen shot 2016-11-04 at 16 30 24](https://cloud.githubusercontent.com/assets/759372/20025491/0683def6-a2ac-11e6-8a9d-7a07aff02164.png)

**Comment by mcomella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user, I want the app to match the UX as designed](https://trello.com/c/vNffsUzV/202-as-a-user-i-want-the-app-to-match-the-ux-as-designed)

**Comment by fluffyemily** [comment]
We have some code in Firefox for iOS that might give you what you need here: https://github.com/mozilla-mobile/firefox-ios/blob/master/Client/Frontend/Widgets/ChevronView.swift
