### ISSUE TITLE
Card not wide enough on plus size devices – can see next card details

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/prox#108]
![simulator screen shot nov 4 2016 18 28 32](https://cloud.githubusercontent.com/assets/759372/20026685/924a4f6e-a2bc-11e6-9a4c-c87c752b935a.png)

You can see the next cards details.

@antlam, is this an issue? If so, how do you want to fix it?

**Comment by mcomella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user, I want the app to match the UX as designed](https://trello.com/c/vNffsUzV/202-as-a-user-i-want-the-app-to-match-the-ux-as-designed)

**Comment by antlam** [comment]
@mcomella let's chat about this after our Sprint stand up meeting - I'd like to understand how we're defining this spacing here :)

**Comment by fluffyemily** [comment]
@antlam I've put in a patch that changes the way we specify the width of a
card from a fixed size to always 16 pixels from the edges of the screen. I
think this meets the criteria of the specs as defined in #11. Does that
meet your criteria?

**Comment by antlam** [comment]
@fluffyemily Sounds like what I was gonna say! thanks!

**Comment by mcomella** [comment]
Fixed by #110.
