### ISSUE TITLE
Implement Home View

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/prox#11]
![apple iphone 7 silver](https://cloud.githubusercontent.com/assets/1119821/19779722/63e2900e-9c50-11e6-871d-95ca580e49e7.png)

**Comment by antlam** [comment]
![spec_home_sizepadding_reviews](https://cloud.githubusercontent.com/assets/1994820/19367629/d7871440-9150-11e6-96a1-aa8ef80558b0.png)
![spec_home_type_reviews](https://cloud.githubusercontent.com/assets/1994820/19367631/d7a0fa5e-9150-11e6-98b1-f89cd5c8c55f.png)
![spec_home_type](https://cloud.githubusercontent.com/assets/1994820/19367633/d7a60cec-9150-11e6-859e-b28cc39e8efe.png)
![spec_home_padding](https://cloud.githubusercontent.com/assets/1994820/19367632/d7a4eff6-9150-11e6-8d2b-c6c979761a9e.png)
![spec_home_sizes](https://cloud.githubusercontent.com/assets/1994820/19367630/d7a0e85c-9150-11e6-92ea-4060297060d9.png)

**Comment by fluffyemily** [comment]
* User should be able to swipe between cards reflecting the order in the carousel
* Closing the card should ensure that the associated place is displayed in the prime location on the carousel (so the carousel is always linked to the currently displayed details card)

**Comment by fluffyemily** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I want to receive an actionable overview of relevant information about places near me, so that my day is not ruined with FOMO](https://trello.com/c/VPWm03rY/49-i-want-to-receive-an-actionable-overview-of-relevant-information-about-places-near-me-so-that-my-day-is-not-ruined-with-fomo)

**Comment by mcomella** [comment]
Notes from Emily's comments on my branch:
* [Animation](http://share.framerjs.com/wriugxdvgenz/)
* "This needs to be another Carousel showing all of the available images. Think about using a UICollectionViewController with paging enabled like we have done in PlaceCarousel, with a UIPageControl to show the position of the current image in the list."
* As no one will be able to see any interactivity on the map, I would ask antlam or vazquez for an asset of a map view that we can use as a background. It would be far less resource intensive and no one will notice

**Comment by mcomella** [comment]
> As no one will be able to see any interactivity on the map,

I feel like having an accurate map in the carousel is important but maybe we can snapshot it and replace the mapview with the snapshot while the places view is open.

**Comment by mcomella** [comment]
@antlam How tall should the review branding logos be?

**Comment by antlam** [comment]
[MVP_assets.zip](https://github.com/mozilla-mobile/prox/files/554644/MVP_assets.zip)

**Comment by mcomella** [comment]
> How tall should the review branding logos be?

via slack: they should be the native image size.

**Comment by mcomella** [comment]
Shadow params via slack:
```
box-shadow: 0px 2px 5px 0px rgba(0,0,0,0.40);
border-radius: 10px;
```

**Comment by mcomella** [comment]
Things still to do (post #91):
* Style website link, make it clickable
* Add expand arrow to description view
* Verify open hours work with real server data
* Split out 
* (too much work?) Text line height styling
* Add Pin to "You are here!" state
* Add shadow to card view

**Comment by fluffyemily** [comment]
@mcomella website link is clickable, it just needs to be underlined. You can do that with `NSAttributedString` like this (although this is Swift 2.3 code so it would need to be Swift 3.0-ified):

```
let underlineAttribute = [NSUnderlineStyleAttributeName: NSUnderlineStyle.StyleSingle.rawValue]
let underlineAttributedString = NSAttributedString(string: "StringWithUnderLine", attributes: underlineAttribute)
myLabel.attributedText = underlineAttributedString
```

**Comment by mcomella** [comment]
I implemented or put all the remaining work into new bugs blocking the Sprint #3 milestone. By the end of the day, I should transform these into trello cards too.
