### ISSUE TITLE
Show caption of a "highlight/top review" from TA/Yelp in Home View

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/prox#119]
![home - a bay - expanded2](https://cloud.githubusercontent.com/assets/1994820/20080322/f7c489ac-a4fd-11e6-9401-b7a04b48b0dd.png)

**Comment by antlam** [comment]
Looking at ways to address feedback from our latest demo. Note: this might be out of scope for Kona.

https://trello.com/c/GUa4CFyx/216-as-a-user-i-want-to-understand-how-the-collapsed-yelp-top-review-wikipedia-summary-etc-is-useful-to-me-so-that-i-can-learn-more-

**Comment by antlam** [comment]
![spec_highlight_dp](https://cloud.githubusercontent.com/assets/1994820/20632920/ea8e936c-b2f5-11e6-8578-e20f04c523c3.png)

![spec_highlight_size](https://cloud.githubusercontent.com/assets/1994820/20632921/ea8f0996-b2f5-11e6-80d4-7b8ddc32e5f0.png)

The type spec will be the same as in issue #11, 
Review text:
- opacity: 0.5;
- font-family: SFUIText-Regular;
- font-size: 14px;
- color: #000000;
- line-height: 22px;

The "reviewed 1 week ago" spec:
- same as "Review text" above

The user name type is:
- font-family: SFUIText-Regular;
- font-size: 16px;
- color: #000000;
- line-height: 24px;

**Comment by fluffyemily** [comment]
@antlam Looking at the data model we have for places and what we pull from Yelp, wikipedia and trip advisor, we don't get anything more than the quote for a source, no reviewer details, details of when the review was posted or images. This makes this as is impossible for Hawaii. As a post Hawaii thing, this is definitely possible though

**Comment by antlam** [comment]
Given that we've already implemented issue 286 for Kona, we should hold off on this for now. UX needs to think about this some more because oarts of this UX don't really make sense to me ATM.

Talking to @liuche a little bit, I have a better understanding now of what data is available so we have some new ideas to flesh out.
