### ISSUE TITLE
Loading Screen Missing

### ISSUE THREAD

**Issue by vazquez** [mozilla-mobile/prox#131]
It seems the loading screen is missing from the current Prox build.

This is the loading animation we have explored in Framer: http://share.framerjs.com/9n2t6pb3umqz/

![screenshot 2016-11-08 15 18 19](https://cloud.githubusercontent.com/assets/1119821/20115535/9c261dda-a5c6-11e6-834e-970aaf5458bf.png)

**Comment by fluffyemily** [comment]
I was unaware of any loading screen or animation being provided to us yet.
Please add specs

**Comment by vazquez** [comment]
## Interaction

GIF showing interaction:

![loading animation](https://cloud.githubusercontent.com/assets/1119821/20148865/8e652d60-a67c-11e6-903d-c876f61347be.gif)

## Assets

- Background – `background_loading.png`
- Blue Loading Dot – `icon_loadingdot.png`

The animation works like this:

- Two circles are positioned at the center
- The sizes of both circles are `height: 100px` and `width: 100px`
- CircleA and CircleB have a background colour of `#0096DD`
- CircleA and CircleB start at `opacity: 0.12`
- CircleA grows to `120px` and changes its opacity to `0.1` while circleB shrinks to `90px` and changes it opacity to `0.3`
- The animation loops back and forth.

**Comment by mcomella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Loading screen improvements](https://trello.com/c/fed9HUKu/180-prox-starts-like-in-this-screenshot-and-stays-there-for-a-really-long-time-like-30-seconds-after-that-it-switches-to-the-card-vi)
