### ISSUE TITLE
Down Arrows for Yelp Top Review Missing

### ISSUE THREAD

**Issue by vazquez** [mozilla-mobile/prox#132]
Component: Summary Card

The up and down arrows next to Yelp Top Review and Wikipedia Summary (when we receive that information) is missing.

Now:

![screenshot 2016-11-08 15 23 48](https://cloud.githubusercontent.com/assets/1119821/20115720/61002128-a5c7-11e6-8fcf-7138d75dfc74.png)

Expected:

![screenshot 2016-11-08 15 21 53](https://cloud.githubusercontent.com/assets/1119821/20115658/18ec6a68-a5c7-11e6-8c8c-7243dfdfe64b.png)

**Comment by mcomella** [comment]
Dupe #106.
