### ISSUE TITLE
Missing "Back to last card Button" on Map View

### ISSUE THREAD

**Issue by vazquez** [mozilla-mobile/prox#134]
Screen: Map View

The breadcrumb and back button is currently not being displayed in the Prox build.

Expected:

![map](https://cloud.githubusercontent.com/assets/1119821/20116056/add4b3fa-a5c8-11e6-8e6c-ccfb5b17e863.png)

**Comment by mcomella** [comment]
@vazquez Didn't we replace this with the map view button after user testing feedback?

**Comment by mcomella** [comment]
@vazquez ping ^

**Comment by vazquez** [comment]
@mcomella Yes! But that was in the Summary Card View, the Map View still needs a way to go back.

**Comment by fluffyemily** [comment]
@vazquez Can you please clarify how this would work. The back button was to return the user to their current location, but if the user doesn't have a current location, what should the button return the user to? The card for the closest place?

**Comment by mcomella** [comment]
fwiw, in eng, we're still not quite sure the back button fits with the app's current mental model (I think @sleroux is expected to follow-up).

That being said, using [some existing iOS UI widgets](http://ivomynttinen.com/blog/ios-design-guidelines) (see UI Elements -> Toolbar), I came up with a quick alternative:
![toolbar](https://cloud.githubusercontent.com/assets/759372/20679140/8cbcdb62-b54e-11e6-90ed-7df751563157.png)

The GPS icon could be "find location closest to you" and the other icon (which you're welcome to improve) is "Go back to previous detail card". My conception is that these would **stay in the map view** and scroll to select the appropriate item.

**Comment by liuche** [comment]
@antlam actually, some clarification would be helpful, I think there's some confusion on what the "back" actually does.

Is this "back" UI meant to A) return the user to their literal current location (Detail card of location closest to their GPS coordinates) or B) return them to the Detail card that they had last seen before switching to the Carousel view?

**Comment by vazquez** [comment]
@mcomella –  We know the UX is not perfect, but I think we need to continue this way for Kona. I think adding a segmented control type of navigation might uncover some more UX bugs.

@fluffyemily @liuche – 

The back button returns the user to the Detail card that they had last seen before switching to the Carousel view. If the card does not exist anymore (because they've moved locations), we then display the closest place.

**Comment by sleroux** [comment]
I think we can all agree that there is value in have a button to return the user back to the detail card. The main concern seems to be the way it's presented. The current style indicates it part of a UINavigationBar which we don't have so it seems out of place. Considering we don't use one, we shouldn't be using this button style. A quick compromise could be to copy the button style we use on the detail screen (circle button + icon). That might also reflect the connection between map <-> detail better.

**Comment by antlam** [comment]
I'm going to spend more time on this tomorrow. 

@mcomella @sleroux @liuche maybe I could hop on vidyo with one of you to get this going faster?

**Comment by mcomella** [comment]
Given that we're introducing new code, should be done EOD.

**Comment by antlam** [comment]
Moving this out of Sprint 5 for now. It's getting a bit hairy and I'm worried about scope creep for Kona.

**Comment by antlam** [comment]
Scoping down this bug to be just about having a "back to where I came from" button.

For example, (WIP) a way for users to return to their card after scrolling a couple cards down the line in the current Map View design. 

![map 5](https://cloud.githubusercontent.com/assets/1994820/20768971/e3793444-b6f4-11e6-813c-63df9cda95a3.png)

**Comment by antlam** [comment]
We'll likely be working on a new "Map/Alternative view" that will change the UI/UX here. Closing for now.
