### ISSUE TITLE
Snapping Interaction of Horizontall Scrolling in Map View

### ISSUE THREAD

**Issue by vazquez** [mozilla-mobile/prox#135]
In the Prox Build, there is no snapping occurring in the cards on the Map View. The intended interaction is shown below. The key difference is in the friction that the card provides to the user, thus making it feel like it snaps back into place.

![map view interaction](https://cloud.githubusercontent.com/assets/1119821/20116118/0615aefc-a5c9-11e6-9aff-fd31b1850793.gif)

**Comment by fluffyemily** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Polish: Add Animation where required](https://trello.com/c/IO2uMqgG/107-polish-add-animation-where-required)

**Comment by sleroux** [comment]
https://github.com/mozilla-mobile/prox/pull/276
