### ISSUE TITLE
Background image Gradient on Summary Cards

### ISSUE THREAD

**Issue by vazquez** [mozilla-mobile/prox#136]
Based on feedback for User Research, the map background we implemented in Summary Cards confused individuals, as we offered no actionable interaction.

We are changing the background image on Summary Cards to offer a blurred image with a gradient.

## Gradient Specs

![home - a bay](https://cloud.githubusercontent.com/assets/1119821/20116888/252e5ca0-a5cc-11e6-80d7-1b7686cf2680.png)

**Comment by mcomella** [comment]
@vazquez would you prefer the gradient to be applied before or after the blur? After appears slightly darker and I'd guess is what we want.

Before:
![simulator screen shot nov 9 2016 17 57 23](https://cloud.githubusercontent.com/assets/759372/20161898/4aa20222-a6a6-11e6-9e75-a81bfb267cb9.png)

After:
![simulator screen shot nov 9 2016 17 56 57](https://cloud.githubusercontent.com/assets/759372/20161903/5164306c-a6a6-11e6-8385-889b9ad84c97.png)

**Comment by vazquez** [comment]
@mcomella – After Mike! Thanks for showing me the difference. 

![](https://media.giphy.com/media/l2Sqir5ZxfoS27EvS/giphy.gif)
