### ISSUE TITLE
Implement Interaction: Map View to Home View

### ISSUE THREAD

**Issue by vazquez** [mozilla-mobile/prox#154]
![home to map](https://cloud.githubusercontent.com/assets/1119821/20186344/a29a5cee-a73d-11e6-8522-12930b5a47a5.gif)

Note: Please disregard the down-arrow in this prototype. The down-arrow has since been deprecated.

**Comment by fluffyemily** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Polish: Add Animation where required](https://trello.com/c/IO2uMqgG/107-polish-add-animation-where-required)

**Comment by sleroux** [comment]
Landed https://github.com/mozilla-mobile/prox/commit/75d78ca506eedd2598c506a9f75e2e15e058b858
