### ISSUE TITLE
antlam@mozilla.com on build #227: Yelp Top Review missing "Read more on Yelp" button

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#155]
Feedback from antlam@mozilla.com : Yelp Top Review missing "Read more on Yelp" button

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/5824636d3a6d35010005777e/25dc564d-1f76-449a-bff8-0970af6eca0b.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Thu Nov 10 2016 17:33:35 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>857.4957</td></tr><tr><td>Build</td><td>227</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Antlam's iPhone 6S</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>81% Unplugged</td></tr><tr><td>Memory free</td><td>166 MB / 1824 MB</td></tr><tr><td>Disk free</td><td>11053 MB / 56428 MB</td></tr><tr><td>Network IP</td><td>10.244.35.11</td></tr></table>

 [Link to buddybuild feedback from build 227](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5824af6f2aceda010071f3bc&bnum=227)

**Comment by antlam** [comment]
@mcomella did you touch this last? :P 

The type spec here should also match the design spec in Issue #11 where we used Wikipedia Summary as the example.

We know that "Last updated" will not be available for Yelp but is there other valuable data we're getting from Yelp that we can put there? Like username, etc?

**Comment by liuche** [comment]
Talked about this with antlam, and decided to just add the link to the Yelp page. "Read more on Yelp" link should be present (in the same place as the Wikipedia "Last Updated..." is in the WP mocks).

Decided that fetching the username, etc would be beyond the scope of MVP.

**Comment by antlam** [comment]
![screen shot 2016-11-24 at 11 03 41 am](https://cloud.githubusercontent.com/assets/1994820/20608330/b72e89ca-b235-11e6-86d0-9f1e2a9e926c.png)

Attaching what the mock looks like for Wikipedia.
