### ISSUE TITLE
Need UX for Event notification when Prox is open, and user is on another Summary Card

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/prox#160]
From talking to @fluffyemily on Slack. 

If a user has Prox open and an event badge needs to be displayed for a location, we don't currently have UI to handle the case where the user is NOT on the corresponding Summary Card. Since a notification won't show if Prox is in the foreground.

UX: 
1. Need a way to notify users IN Prox, that an event is about to start for a given location
2. Need to animate in Event Banner UI if an event is about to start and the user is on that exact location card.

**Comment by vazquez** [comment]
Need to animate in Event Banner UI if an event is about to start and the user is on that exact location card.

### Proposal

![event animation](https://cloud.githubusercontent.com/assets/1119821/20228949/c8ab3748-a821-11e6-9374-f26dcc0b1e9e.gif)

**Comment by antlam** [comment]
@vazquez nice! question: what happens if the user isn't on the Hilton card but is on say... the Tropics Ale House card? does it force-swtich them to the Hilton card automatically?

**Comment by vazquez** [comment]
@antlam – I think you're asking about the other task in the card, right? If so, here is a proposal.

**Task:** Need a way to notify users IN Prox, that an event is about to start for a given location

### Proposal:

![artboard](https://cloud.githubusercontent.com/assets/1119821/20234489/2e11f414-a84a-11e6-81ee-056404e45cc5.png)

**Comment by antlam** [comment]
@vazquez yep! Sorry I must've glazed over the issue title. I see it now! 👍

**Comment by fluffyemily** [comment]
So, the event alert banner is possible and can be achieved in the scope of Hawaii. We would need some sort of UI for users on iOS9 anyway as they don't get notifications in-app, and I can squash the display of notifications in app for iOS10 and just display the banner

the event arriving while you are looking at the current card animation is a little ambitious for sprint 5 given the large amount of animation work already to be done. I would ask for a simpler animation for Hawaii (maybe just the banner displaying), with the more complex animation brought in for post hawaii

**Comment by fluffyemily** [comment]
additionally, for the iOS10 event notification in app, instead of simply squashing the notification toast, we could swap it to play a sound, so it would ring around the time the banner was animating in?

**Comment by antlam** [comment]
@vazquez could you follow up here to see how we want to scope it down for Kona? 

I'm not sure about sounds, but I think we can decide to polish in a future issue if we want something for Kona. :)

**Comment by vazquez** [comment]
On the docket for tomorrow :+1: I had to unblock Mike first with
categories.

**Comment by fluffyemily** [comment]
@vazquez any updates on what you want for this? We're running out of time to fit this work in.

**Comment by vazquez** [comment]
![artboard copy](https://cloud.githubusercontent.com/assets/1119821/20673269/79032820-b552-11e6-93ea-13acfa7ce4fd.png)

## Animation

Regarding animation, could we do a cross-fade?

![simple event banner](https://cloud.githubusercontent.com/assets/1119821/20673278/7cd988ae-b552-11e6-9f82-739c0fd1ef57.gif)
