### ISSUE TITLE
[Crash] NSInternalInconsistencyException: you can't call -sendResponse: twice nor after encoding it [Build #247]

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#161]
Buddybuild detected a crash from mpopova@mozilla.com
`Prox/AppDelegate.swift` line 9`
```swift
import UIKit
import Firebase

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate { <-- CRASHED

    var window: UIWindow?
    var placeCarouselViewController: PlaceCarouselViewController?

    private var authorizedUser: FIRUser?
```

[View File](https://github.com/mozilla-mobile/prox/blob/f3bd1ae87e473385d3721c71ba6defd6e39a9126/Prox/AppDelegate.swift#L9) | [View Full Crash Details](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/crashreport/27b13f33f4104e50b74674421bd87158)

**Comment by sarentz** [comment]
Crash report from mpopova@mozilla.com

**Comment by mcomella** [comment]
Line 9 is the class declaration so that isn't super useful.

StackOverflow says it could be from calling a completionHandler twice. We call a completion handler in AppDelegate in func application(_ application: UIApplication, performFetchWithCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) { but I see no indication that we call it twice (we always return the result of the handler).

Possibilities:
* There is some part of the app lifecycle that I'm not aware of that causes the completion handler to be called twice (e.g. this background fetch method is called twice)
* There is another system method getting called (outside of AppDelegate) where we call a completion handler twice

**Comment by mcomella** [comment]
The first crash occurred on Nov. 12, 8am PST. #150 & #156 merged around Nov. 11, 6:30am PST making this most likely a regression from these changes. The PRs merged before them were largerly UI updates/bug fixes and so are likely unrelated.

**Comment by mcomella** [comment]
We don't call `completionHandler` if `placeCarouselViewController` is nil – I wonder if that's an issue? Code:

```swift
    func application(_ application: UIApplication, performFetchWithCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        guard let currentLocation =  placeCarouselViewController?.getCurrentLocation() else { return completionHandler(.noData) }
        placeCarouselViewController?.eventNotificationsManager.fetchEvents(forLocation: currentLocation) { (events, error) in
            if let _ = error {
                return completionHandler(.failed)
            }

            guard let events = events,
                !events.isEmpty else {
                return completionHandler(.noData)
            }

            completionHandler(.newData)
        }

    }
```

**Comment by rnewman** [comment]
Make sure you don't have two concurrent `NSURLSession`s running in the background. If they both call the completion handler, the second one will cause this crash.

**Comment by rnewman** [comment]
This looks relevant:

http://stackoverflow.com/questions/34953483/background-fetch-delegate-called-twice-on-device-when-simulate-background-fetch
http://stackoverflow.com/questions/33105744/performfetchwithcompletionhandler-called-twice-when-simulating-with-xcode

**Comment by rnewman** [comment]
There's a settable minimum background fetch interval, which might also help avoid multiple concurrent fetches.

**Comment by mcomella** [comment]
rnewman and bnicholson pointed out that the notifications manager replaces its completion handler each time `fetchEvents` is called so if `fetchEvents` is called twice, the same completion handler may be called twice.

**Comment by thebnich** [comment]
> Edit: bnicholson pointed out the guard prior to fetchEvents will prevent this case from happening (I wonder if it'd be safer to change the second use of the placeCarouselViewController to ! to safeguard our assumptions).

A more Swift-y approach would be something like this:
```
guard let viewController placeCarouselViewController,
      let = currentLocation = placeCarouselViewController?.getCurrentLocation() else {
    return completionHandler(.noData)
}

viewController.eventNotificationsManager.fetchEvents(...)
```
