### ISSUE TITLE
Create an app icon for our baby Prox

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/prox#164]
Working on something... and trying to stay consistent with Apple guidelines, and all the work that Martell has done, all while accurately representing our in product UI.

Anywho! WIP here, wanted to show some progress/progression.

<img width="648" alt="screen shot 2016-11-14 at 7 56 47 pm" src="https://cloud.githubusercontent.com/assets/1994820/20264275/a5c99e46-aaa5-11e6-9c34-7af3b1a995bc.png">

**Comment by antlam** [comment]
Can we try these?

![180 - iphone 6 plus](https://cloud.githubusercontent.com/assets/1994820/20577958/b0a84b5c-b179-11e6-91ad-285aa1750bf1.png)

[App icon.zip](https://github.com/mozilla-mobile/prox/files/609949/App.icon.zip)

**Comment by mcomella** [comment]
@antlam I’m getting different pt values in xcode from your assets:

<img width="755" alt="screen shot 2016-11-23 at 16 51 06" src="https://cloud.githubusercontent.com/assets/759372/20583666/cf6ff5cc-b1a0-11e6-83d9-ed8e65dca4ad.png">

* It looks like your assets are x2, but maybe xcode “pts” aren’t equivalent to pixels.
* We’re also missing the “notification” asset

**Comment by antlam** [comment]
Found a softer gradient worked better with the help of Martell!

![icon](https://cloud.githubusercontent.com/assets/1994820/20609364/63771c38-b240-11e6-8b91-60caad2a5631.png)

@mcomella Try these: I used the same template as the ones from Focus 2.0

[App icon 2.zip](https://github.com/mozilla-mobile/prox/files/612124/App.icon.2.zip)

**Comment by mcomella** [comment]
Here's what I have:

![screen shot 2016-11-28 at 14 39 44](https://cloud.githubusercontent.com/assets/759372/20689126/9f9b6332-b578-11e6-89f4-d654ee987b25.png)

@fluffyemily Did I do this right? The iPad settings/spotlight icons are identical to the iphone so I left them out but I don't know if they're rescaling the iPad app asset or using the iPhone settings/spotlight asset. In any case, I doubt we're really focused on iPads so maybe we shouldn't worry too much about it. fwiw, Focus duplicates the icons (but didn't bother disabling the CarPlay asset pack so I'm not super trusting of that) and Firefox-ios seems to be all over the place (some assets are there and others are missing).

@antlam We're missing the 20pt icons for notifications. I don't know if iOS will use a fallback, but it'd look best with the appropriate sized assets. fwiw, Firefox-ios and Focus are also missing this icon so it'll probably use a fallback.

**Comment by antlam** [comment]
> @antlam We're missing the 20pt icons for notifications. I don't know if iOS will use a fallback, but it'd look best with the appropriate sized assets. fwiw, Firefox-ios and Focus are also missing this icon so it'll probably use a fallback.

Yeah I just basically supplied the same icons I did for Focus. Let me know if you still need some though!

**Comment by fluffyemily** [comment]
@antlam we need that notification icon

 
![screen shot 2016-11-29 at 14 44 35](https://cloud.githubusercontent.com/assets/12613048/20714025/88fc43a6-b642-11e6-8231-6f14c33d81a8.png)

**Comment by antlam** [comment]
@mcomella @fluffyemily 

sorry! try these! 

![notifications](https://cloud.githubusercontent.com/assets/1994820/20719775/cba76680-b611-11e6-9e1b-a04687c5a8ad.png)
![notifications 2x](https://cloud.githubusercontent.com/assets/1994820/20719774/cba690fc-b611-11e6-8e39-cf1ffc9b6bf3.png)
![notifications 3x](https://cloud.githubusercontent.com/assets/1994820/20719776/cbacda52-b611-11e6-814e-17e3c37bb973.png)
