### ISSUE TITLE
Travel times missing (no error state)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/prox#167]
Maria noticed this issue:
![img_4880](https://cloud.githubusercontent.com/assets/759372/20278046/113e3b80-aa58-11e6-86ee-67de9c9bfc1c.PNG)

I'd guess the travel times were unable to be fetched but we didn't update the UI correctly. How do we handle the error states?

**Comment by mcomella** [comment]
@vazquez What should we display when the travel times could not be retrieved?

**Comment by mcomella** [comment]
Note: we should still allow (and include an affordance for) users to route to the location even if we can't obtain travel times.

**Comment by vazquez** [comment]
@mcomella – Let's display this when travel times are not able to be retrieved.

If tapped, a person can still open the location in Google Maps (or Apple Maps if GMaps not installed)

![home - current](https://cloud.githubusercontent.com/assets/1119821/20361044/1c1d1de8-ac04-11e6-95dc-07aa74eeffb1.png)

**Comment by antlam** [comment]
@mcomella I'm just trying to get some more context around this. 

Why is this happening sometimes? Is this something we'll be resolving in the future?

**Comment by mcomella** [comment]
> Why is this happening sometimes? Is this something we'll be resolving in the future?

This should be fixed with #275.
