### ISSUE TITLE
Loading Screen IF wait is longer than 60 seconds

### ISSUE THREAD

**Issue by vazquez** [mozilla-mobile/prox#175]
Upon first launch of the app, we show a loading screen while we populate the information in the background. In the event that we can't populate event data, we need to show a message inviting people to restart this Beta App.

![home - tropics ale house copy 7](https://cloud.githubusercontent.com/assets/1119821/20352417/33d39c4c-abe5-11e6-94e9-e23df8184de8.png)

![home - tropics ale house copy 7](https://cloud.githubusercontent.com/assets/1119821/20352603/d6977f70-abe5-11e6-9620-bc01c97171ee.png)

**Comment by fluffyemily** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Loading screen improvements](https://trello.com/c/fed9HUKu/180-loading-screen-improvements)

**Comment by sleroux** [comment]
@vazquez What do you think about fading in the label/buttons like dis

![error_fade_in](https://cloud.githubusercontent.com/assets/434322/20409458/ab27d314-ace7-11e6-8eb6-c746a6b2bcad.gif)

**Comment by vazquez** [comment]
Yeah Steph! Let's do that 🙂
