### ISSUE TITLE
Finalize Yelp categories to restrict

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/prox#178]
Follow-up to #49. Once it lands, we should see what UX thinks and see where else we can edit the category filters.

After #49, we hide a place if its categories match *all* of the following categories:

> "auto",
                                                  "bicycles",
                                                  "education",
                                                  "financialservices",
                                                  "health",
                                                  "homeservices",
                                                  "localservices",
                                                  "professional",
                                                  "realestate",
                                                  "religiousorgs")

In a 4km radius from the hotel, 0 places were filtered under this criteria.

**Comment by mcomella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user I want to see the most useful places when I open the app so that I can make better decisions about my next step](https://trello.com/c/IBEHIXNb/149-as-a-user-i-want-to-see-the-most-useful-places-when-i-open-the-app-so-that-i-can-make-better-decisions-about-my-next-step)

**Comment by mcomella** [comment]
Next steps:
* UX will go through the full category list (yelp API v2 or v3 TBD) to identify which sub-categories we might want to block
* UX will decide if we to hide places if one of their categories matches a UX-specified hide category or if *all* of their categories match UX-specified hide categories
* With list ^, eng to implement

Engn notes:
* We're whitelisting the top-level categories
  * We can filter the initial yelp query by these categories

**Comment by mcomella** [comment]
Note to self: remoteConfig! If you implement this soon, UX can update everything themselves (assuming the logic doesn't need to change).

**Comment by mcomella** [comment]
Spoke with @vazquez:
* UX will continue to create a list of categories we want to hide.
  * If UX specifies a category, I will hide that category *and all of its children*. This is for simplicity: UX has to specify fewer things and we don't need more complex logic (e.g. "Hide category except for children...")
  * I will add a parameter to Firebase remote config where we can dump a csv of categories and the client will hide that list of categories. This will allow the designers to quickly update the category list themselves.
    * I gave Ricardo [a script to convert a newline-separated file into a csv](https://gist.github.com/mcomella/142b8339e34b24a02d6233bc3cb93a42) to make creating a csv easier
* Still TBD: UX will decide if we to hide places if one of their categories matches a UX-specified hide category or if all of their categories match UX-specified hide categories

Yelp API investigations:
* If a top-level Yelp category has children, places can still have that top-level category as a category.

**Comment by mcomella** [comment]
> I will add a parameter to Firebase remote config where we can dump a csv of categories and the client will hide that list of categories.

**Important note:** if UX wants to change the top-level categories, you have to tell engineering – we’re filtering the query based on those categories atm so if you make changes to Firebase, it won’t be reflected in the app results

**Comment by vazquez** [comment]
**Update:** I have finished going through the 0.5hr JSON file. I have an updated CSV file with all the categories to exclude.

CSV file can be found [here](https://gist.github.com/vazquez/a6ee1f45cf137ab8034345037faeb52a).

**Comment by mcomella** [comment]
Got new lists for Ricardo based on hiding the subcategories in [this csv](https://gist.github.com/mcomella/147a14086a8da51f638d05e1967070f8) (that Ricardo emailed me):
* [Hide if all place's categories are matching hidden categories][all] (410 places)
  * [Diff from previous category criteria to new "match all" category criteria][bigdiff] (227 places)
* [Hide if one place's categories match hidden categories][one] (382 places)
* [Diff between all and one criteria][diff]

[all]: https://gist.github.com/mcomella/931d45335620a5b492c84646e30d84ac
[one]: https://gist.github.com/mcomella/221de696c2c9081007b4fb159f3e5058
[diff]: https://gist.github.com/mcomella/8a05663ded4714994da09b813b3803f5
[bigdiff]: https://gist.github.com/mcomella/147a14086a8da51f638d05e1967070f8

**Comment by mcomella** [comment]
Ricardo's latest list is in Firebase and we'll merge these into the defaults in #250.

**Comment by mcomella** [comment]
@antlam @vazquez Can we close this?

**Comment by antlam** [comment]
Let's close this now. We can reopen new issues as necessary
