### ISSUE TITLE
Continue tweaking ratings filter

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/prox#179]
Follow-up to #49. After that lands, we should see what UX thinks and tweak the params.

After #49, we filter places with the following criteria:
```swift
        if (rating < 2.5) ||
                (rating == 3 && reviewCount > 3) ||
                (reviewCount <= 3 && rating < 5) {
            return false // hide
        } else {
            return true // show
        }
```

In a 4km radius from the hotel, this filters one place: "three-fat-pigs-waikoloa-2".

**Comment by mcomella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user I want to see the most useful places when I open the app so that I can make better decisions about my next step](https://trello.com/c/IBEHIXNb/149-as-a-user-i-want-to-see-the-most-useful-places-when-i-open-the-app-so-that-i-can-make-better-decisions-about-my-next-step)

**Comment by mcomella** [comment]
The logic was contradictory – I've updated the criteria in the doc and we should match it. Specifically:
```
if rating < 2.5 OR // crappy
    (rating == 3 AND review_count > 3) // known to be mediocre
  HIDE
else
  SHOW
```

**Comment by mcomella** [comment]
Spoke with @antlam: the ratings logic is basically done. We need to update the iOS client to match the new logic ^ and the server, if it's filtering by rating.

@liuche @jhugman Is the server filtering by rating?

**Comment by jhugman** [comment]
> Is the server filtering by rating?
No, [this card][1] covers that case.

  [1]:
https://trello.com/c/WQU12rOD/238-as-a-user-i-wish-that-the-server-did-more-filtering-of-places-so-my-phone-didn-t-need-to-download-quite-so-much
