### ISSUE TITLE
Travel times don't load when swiping quickly (rate limited?)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/prox#184]
Some travel times don't load: I assume we're getting rate-limited when swiping quickly through a full carousel (~30 items).

Question: Are we querying once for place or querying multiple times for each place? I don't think we wait for an in-flight query to finish before requesting another one and I think we have an issue with loading the places data more than once, compounding the issue.

**Comment by mcomella** [comment]
It looks like we reload the travel times each time a cell is shown in the map view (PlaceCarousel#91):
```swift
        if let location = locationProvider?.getCurrentLocation() {
            place.travelTimes(fromLocation: location, withCallback: { travelTimes in
                self.setTravelTimes(travelTimes: travelTimes, forCell: cell)
            })
        }
```

**Comment by fluffyemily** [comment]
Might be worth storing travel times by location, so we update our travel times if we have moved a certain distance from the location we were in since we calculated the last travel time for this location, but don't have to do it every time if we haven't moved far since last time.
