### ISSUE TITLE
antlam@mozilla.com on build #253: TripAdvisor rating not showing up in Map View for some cards

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#188]
Feedback from antlam@mozilla.com : TripAdvisor rating not showing up in Map View for some cards

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/582ae8fd93d9f7010000c759/ae4df1b8-9852-4e57-86ed-006965c72e98.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Nov 16 2016 03:38:24 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>4012.382</td></tr><tr><td>Build</td><td>253</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Antlam's iPhone 6S</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>60% Unplugged</td></tr><tr><td>Memory free</td><td>210 MB / 1819 MB</td></tr><tr><td>Disk free</td><td>9521 MB / 56428 MB</td></tr><tr><td>Network IP</td><td>10.247.33.214</td></tr></table>

 [Link to buddybuild feedback from build 253](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=582bd4b013f8bd01009cdc58&bnum=253)

**Comment by mcomella** [comment]
Dupe #157.

**Comment by mcomella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [TripAdvisor rating not showing up in Map View for some cards](https://trello.com/c/apa0pSBF/229-tripadvisor-rating-not-showing-up-in-map-view-for-some-cards)
