### ISSUE TITLE
antlam@mozilla.com on build #253: Missing Wikipedia Summary

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#189]
Feedback from antlam@mozilla.com : Missing Wikipedia Summary

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/582ae8fd93d9f7010000c759/a624f357-99ec-4131-8e77-f7175db2ad52.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Nov 16 2016 03:39:39 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>26.85466</td></tr><tr><td>Build</td><td>253</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Antlam's iPhone 6S</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>59% Unplugged</td></tr><tr><td>Memory free</td><td>244 MB / 1817 MB</td></tr><tr><td>Disk free</td><td>9533 MB / 56428 MB</td></tr><tr><td>Network IP</td><td>10.247.33.214</td></tr></table>

 [Link to buddybuild feedback from build 253](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=582bd4fb13e07e0100f0beef&bnum=253)

**Comment by jhugman** [comment]
Looking at the Firebase console,
https://console.firebase.google.com/project/prox-server-cf63e/database/data/venues/details/blue-wilderness-dive-adventures-waikoloa
it appears the data is not present. This is a problem with Factual
Crosswalk.

**Comment by mcomella** [comment]
It doesn't appear "Blue Wilderness Dive Adventures" has a wikipedia page: https://en.wikipedia.org/w/index.php?search=blue+wilderness+dive+adventures&title=Special:Search&searchToken=96ynp39210svtdhvm29c7t9dm

Last I tested, Wikipedia data works where available – there just aren't any places in the radius we currently query that have wiki data.

@antlam What do you expect here?

**Comment by antlam** [comment]
@mcomella ok that's fine! 

thanks for clarifying. :)

**Comment by mcomella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Missing Wikipedia Summary](https://trello.com/c/2ICblR7c/230-missing-wikipedia-summary)
