### ISSUE TITLE
Resolve broken constraint errors

### ISSUE THREAD

**Issue by fluffyemily** [mozilla-mobile/prox#190]
We currently have a number of instances of broken layout constraints caused by the hiding and reshowing of views within the carousel and details cards. We should address these to ensure we don't get any unexpected layout behaviour during execution

**Comment by sleroux** [comment]
Running the app on latest master (a974d6c0d7901d33b2a1379fb36d8c6a14924d40) I haven't seen any constraint warnings when I navigate around, expand/collapse things, or transition.

**Comment by fluffyemily** [comment]
This is still an issue. Product -> Edit Scheme -> Run -> Arguments and re-enable OS_ACTIVITY_MODE and you will see the constraint errors. I didn't realise that getting rid of the guff of logging would also suppress UIViewAlertForUnsatisfiableConstraints errors

**Comment by fluffyemily** [comment]
Resolved in #287 - lowered the priority of height and bottom constraints so they didn't clash with hidden and spacing constraints
