### ISSUE TITLE
Handle updating UI for place pop-in (e.g. map view places count)

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/prox#198]
While in the card view the button for the map view showed an incorrect number of results. Likely hard to reproduce with a cached location.

* First run on a new location 
* Clicked on early results that appeared in the default view
* More results popped in and I was able to swipe between them in the card view
* The map view button stayed at 2 when there were obviously more than 2 items listed

* going back to the map view updated the count to the correct number

**Comment by mcomella** [comment]
> More results popped in and I was able to swipe between them in the card view

We originally wrote the code to expect static places data. However, pop-in is an issue now that we do custom location querying – we have to make sure we handle updating all aspects of the UI, not just place count.
