### ISSUE TITLE
No time value shown for directions

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/prox#199]
It seems like there was some geolocation jitter just before this occurred. Locations that were next door showed 15 min min walk. Then the location data updated and there was a spinner shown for 20s I swiped to the next card and also saw the spinner. All the other cards updated to the correct walking time but the one I swiped to after the location update was triggered.

![screen shot 2016-11-16 at 1 08 13 pm](https://cloud.githubusercontent.com/assets/250273/20366027/41ff1684-abfe-11e6-87b4-3ee9fce029a4.png)

**Comment by kbrosnan** [comment]
This also prevents the user from launching the external map app.

**Comment by mcomella** [comment]
Thanks for filing – dupe #167.
