### ISSUE TITLE
at the PDX office 8 of 20 intresting places are body care

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/prox#200]
I know that #49 allows for user curation of the data. Though this seems like a poor default for finding interesting things to do in a new city.

Body care 8 (6 hair salons, 1 waxing, 1 tattoo)
Food 4
Shopping 3
Tours 2
Hotel 1
Florist 1
Passport photo/notary 1

https://www.yelp.com/c/portland/arts feels closer to what we are aiming for. https://www.tripadvisor.com/Attractions-g52024-Activities-Portland_Oregon.html feels even closer.

**Comment by mcomella** [comment]
We haven't tweaked the query results much yet – I expect this to get duped to #49, or its follow-ups.

**Comment by mcomella** [comment]
We landed the major query param bugs so I don't think this is actionable – Anthony and Ricardo will file new issues if they see anything.
