### ISSUE TITLE
mheubusch@mozilla.com on build #274: Vet showing up as a category

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#215]
Feedback from mheubusch@mozilla.com : Vet showing up as a category 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/582c90352d9fa90100991a16/981c8efa-5ed2-43db-85cd-84c7f05e98ac.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Fri Nov 18 2016 18:36:30 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>54367.97</td></tr><tr><td>Build</td><td>274</td></tr><tr><td>Device type</td><td>iPhone 7</td></tr><tr><td>Device name</td><td>Michelle's iPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>18% Unplugged</td></tr><tr><td>Memory free</td><td>40 MB / 1426 MB</td></tr><tr><td>Disk free</td><td>103975 MB / 116315 MB</td></tr><tr><td>Network IP</td><td>0.0.0.0</td></tr></table>

 [Link to buddybuild feedback from build 274](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=582f4a2e05613401004913f4&bnum=274)

**Comment by kbrosnan** [comment]
Similar to #200
