### ISSUE TITLE
if image is not present do not display carousel

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/prox#217]
Feels rather broken to swipe through a set of blank images
![screen shot 2016-11-18 at 2 01 14 pm](https://cloud.githubusercontent.com/assets/250273/20448171/91e263be-ad97-11e6-82b2-fded2072b098.png)

**Comment by mcomella** [comment]
Hiding the carousel is hard so we don't want to change the view, but consider the following for the sprint. If no images:
* Change carousel to be one dot so you can't swipe through empty images
* Set BG to a different, less obvious color.

**Comment by antlam** [comment]
@vazquez has an error state for this on the Map view. We should just use that here for this sprint.

**Comment by mcomella** [comment]
To be clear, the error state is a placeholder image while we wait for the image to load – this should be trivial with AFNetworking (there is a placeholder arg to load image).

Make sure we cancel any in-flight requests (if load image does not do so already).

**Comment by vazquez** [comment]
The image placeholder has been placed in the Assets folder.

`image-placeholder.png`
`image-placeholder@2x.png`
`image-placeholder@3x.png`

https://www.dropbox.com/sh/b30k7wfqerbbb7f/AACdQhl1QKr0MnQyly6KGngSa?dl=0

This is what the image placeholder should look like:

![home - tropics ale house copy 2](https://cloud.githubusercontent.com/assets/1119821/20765599/fe0c3b24-b700-11e6-8f2b-4e0e0c12d851.png)

**Comment by mcomella** [comment]
Design decision from @vazquez on slack:
* Set the background image to the place holder image of the hotel we used at the start of the project when entering a view with a placeholder
