### ISSUE TITLE
`PlacesController.updatePlaces` is called frequently, with no short-circuit

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/prox#218]
`PlacesController.`updatePlaces is called every time `PlaceCarouselViewController.viewWillAppear` is called.

Each time `updatePlaces` is called, we ping the server with our location, query the firebase, and replace all our in-memory places with a new set. In my particular case, I was trying to add a travel times cache on the places and they'd get wiped out each time, requiring recomputation.

Since we don't have firebase persistence enabled, it's also possible each time we query the firebase, we'll pulling down redundant data.

We should also check to see if there's anywhere else the places may be getting replaced from (e.g. place details, events).

CC @fluffyemily for awareness.

**Comment by fluffyemily** [comment]
update places will only get called when the app opens and when you close the details view. We should add a check to ensure that the location has changed significantly since the last fetch to ensure we are not fetching for a location we already have data for.

**Comment by mcomella** [comment]
I haven't dug in but it seems that the set of places gets updated twice just from launching the app.

**Comment by jhugman** [comment]
>
> Since we don't have firebase persistence enabled, it's also possible each
> time we query the firebase, we'll pulling down redundant data.

This is a worry. I was under the impression that persistence was enabled.

I haven't dug in but it seems that the set of places gets updated twice
> just from launching the app.
>
This is once at `viewDidAppear` and once when the location is set. We
prevent a race by only allowing one update to happen at a time.

**Comment by fluffyemily** [comment]
I am resolving this _right now_

**Comment by mcomella** [comment]
@fluffyemily Did you close this because it was fixed in #226?

**Comment by fluffyemily** [comment]
Yes
