### ISSUE TITLE
Map view image & travel times: loading & error states

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/prox#219]
@vazquez In map view, we make async requests for images and travel times – we'll need to add a placeholder while we wait for these to load. fwiw, in practice with a fast connection, we won't see this, except for travel times if we're not able to solve #184.

Then we need the error state, if the request fails.

**Comment by vazquez** [comment]
### Design

- We have an image placeholder while we wait to retrieve images.
- While we wait for travel times, we will simply show a `Locating...` text string. If we cannot retrieve travel times, we substitute the text string with `Travel time unknown`

![image loading](https://cloud.githubusercontent.com/assets/1119821/20489993/83560f0e-afda-11e6-89d1-585b987ccc21.png)


### Assets

The image loading assets is in the Assets folder. https://www.dropbox.com/sh/b30k7wfqerbbb7f/AACdQhl1QKr0MnQyly6KGngSa?dl=0

`image-loading.png`
`image-loading@2x.png`
`image-loading@3x.png`

**Comment by fluffyemily** [comment]
@vazquez - does this mean you want us to remove the spinner that we
currently display while calculating travel times and replace it with the
word "Locating"?

**Comment by vazquez** [comment]
@fluffyemily The spinner only shows in Summary Card view though, right? We don't have a placeholder for Map View, from what I gather from @mcomella.

**Comment by mcomella** [comment]
> @fluffyemily The spinner only shows in Summary Card view though, right? We don't have a placeholder for Map View, from what I gather from @mcomella.

This is correct.

**Comment by fluffyemily** [comment]
Ah yeah. Sorry. Didn't read the title clearly!

**Comment by antlam** [comment]
@mcomella if "Travel time unknown" how does the user "Try again"? or what can they do about it?

**Comment by mcomella** [comment]
> @mcomella if "Travel time unknown" how does the user "Try again"? or what can they do about it?

The reason we get "Travel time unknown" is that Apple rate-limits us and does not provide the travel time. We retry the next time the card is shown (though we may still be rate-limited).

Speaking with @vazquez, the suggestion of removing the error state and keeping "Locating..." makes sense with the back-end.
