### ISSUE TITLE
mheubusch@mozilla.com on build #274: I'm in Ohio and Prox isn't showing anything. Will reinstall…

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#221]
Feedback from mheubusch@mozilla.com : I'm in Ohio and Prox isn't showing anything. Will reinstall and see what happens 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/582c90352d9fa90100991a16/133b39a7-b441-4aad-8ce8-4a292e69b8c0.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Sat Nov 19 2016 23:07:57 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>93530.56</td></tr><tr><td>Build</td><td>274</td></tr><tr><td>Device type</td><td>iPhone 7</td></tr><tr><td>Device name</td><td>Michelle's iPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>28% Unplugged</td></tr><tr><td>Memory free</td><td>136 MB / 1551 MB</td></tr><tr><td>Disk free</td><td>103831 MB / 116315 MB</td></tr><tr><td>Network IP</td><td>10.224.148.226</td></tr></table>

 [Link to buddybuild feedback from build 274](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5830db4d9bd3790100357dec&bnum=274)

**Comment by vazquez** [comment]
This issue can be closed once #175 and #131 are resolved.

**Comment by mcomella** [comment]
Dupe #363.
