### ISSUE TITLE
Implement the detail view card transition animation

### ISSUE THREAD

**Issue by fluffyemily** [mozilla-mobile/prox#233]
As demonstrated in this framer.js video

http://share.framerjs.com/0482ps2palnz/

And this one
http://share.framerjs.com/fnvrr4a09266/

**Comment by fluffyemily** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Polish: Add Animation where required](https://trello.com/c/IO2uMqgG/107-polish-add-animation-where-required)

**Comment by sleroux** [comment]
https://github.com/mozilla-mobile/prox/pull/282
