### ISSUE TITLE
Spinner and show on map shown at the same time

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/prox#234]
I am seeing the view on map and the spinner at the same time. Not sure how I got into this state.

![screen shot 2016-11-21 at 11 25 48 am](https://cloud.githubusercontent.com/assets/250273/20498977/3806facc-afe4-11e6-8514-fd6c2712f841.png)

**Comment by mcomella** [comment]
Making robustess changes for travel times in #185 – hopefully I'll be able to close this with that patch.
