### ISSUE TITLE
Dealing with multiple service results from Factual

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/prox#235]
If there are two or more service articles for a location then we may choose the wrong one. 

Portlandia a statue on a city building is detected as being interesting in Yelp. The Factual place ID is http://factual.com/9a048c37-3547-4cf5-a404-daadf9fdbb45 which is for the Portland city government offices as well as the statue. https://en.wikipedia.org/wiki/Portland_Building and https://en.wikipedia.org/wiki/Portlandia_(statue) we choose the Portland Building article. It is confusing without local knowledge that the statue is part of the building.

The same issue can be found with the TripAdvisor data. The first link is for the Portland Building and the second is for the Portlandia statue. https://www.tripadvisor.com/Attraction_Review-g52024-d126566-Reviews-The_Portland_Building-Portland_Oregon.html vs. https://www.tripadvisor.com/Attraction_Review-g52024-d269457-Reviews-Portlandia-Portland_Oregon.html

![screen shot 2016-11-21 at 2 51 24 pm](https://cloud.githubusercontent.com/assets/250273/20503981/041c2816-affa-11e6-94cd-1ed430286332.png)

**Comment by jhugman** [comment]
>  It is confusing without local knowledge

We do not have the signals from the APIs to make this determination at this point. We also don't have the infrastructure to make this determination from the unstructured text.
