### ISSUE TITLE
sarentz@mozilla.com on build #358: Waiting

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#245]
Feedback from sarentz@mozilla.com : Waiting

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58345f0f1709f80100415b44/514e9d00-448a-411e-b972-d5b192e8e800.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Tue Nov 22 2016 19:24:03 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>155.4768</td></tr><tr><td>Build</td><td>358</td></tr><tr><td>Device type</td><td>iPhone 6s Plus</td></tr><tr><td>Device name</td><td>Stefan's iPhone 6s Plus</td></tr><tr><td>Screen size</td><td>414</td></tr><tr><td>Screen size</td><td>414px by 736px</td></tr><tr><td>Battery</td><td>78% Unplugged</td></tr><tr><td>Memory free</td><td>84 MB / 1710 MB</td></tr><tr><td>Disk free</td><td>12508 MB / 116073 MB</td></tr><tr><td>Network IP</td><td>192.168.0.13</td></tr></table>

 [Link to buddybuild feedback from build 358](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=58349b53fe69ba0100e242f2&bnum=358)

**Comment by fluffyemily** [comment]
This should be resolved by #226
