### ISSUE TITLE
Event has no relation to the card shown

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/prox#247]
Most of the events I see have no relation to the card that is shown. For example this steak house we claim is holding an after school event.

![screen shot 2016-11-22 at 1 18 31 pm-crop](https://cloud.githubusercontent.com/assets/250273/20542642/56515152-b0b7-11e6-81ef-0a10d3ed4ae1.png)

The eventful event is http://portland.eventful.com/events/after-school-leap-program-cesar-chavez-/E0-001-094779786-6

**Comment by mcomella** [comment]
I wonder if this is a card re-use problem... x_x
