### ISSUE TITLE
jmoradi@mozilla.com on build #358: Not a bug. It found RP, which is the world's greatest pizza…

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#257]
Feedback from jmoradi@mozilla.com : Not a bug. It found RP, which is the world's greatest pizza place. And the reason we bought our house here. This app is working!

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58345f0c1709f80100415b43/3b2faae9-3d16-4942-b873-8c2271c0063e.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Nov 23 2016 12:23:35 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>69.60922</td></tr><tr><td>Build</td><td>358</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>iPhone</td></tr><tr><td>Screen size</td><td>320</td></tr><tr><td>Screen size</td><td>320px by 568px</td></tr><tr><td>Battery</td><td>100% Unplugged</td></tr><tr><td>Memory free</td><td>43 MB / 1718 MB</td></tr><tr><td>Disk free</td><td>4536 MB / 56382 MB</td></tr><tr><td>Network IP</td><td>0.0.0.0</td></tr></table>

 [Link to buddybuild feedback from build 358](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=58358a47a6dadf0100d7a553&bnum=358)

**Comment by fluffyemily** [comment]
Not a bug
