### ISSUE TITLE
antlam@mozilla.com on build #372: Padding in between "7 min/ Closed" and "Walking/ opens at"…

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#259]
Feedback from antlam@mozilla.com : Padding in between "7 min/ Closed" and "Walking/ opens at" is too large 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/583589b772e92c01002712a1/5a84f73e-5a3b-4c11-b61c-f9a2f7c945fa.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Nov 23 2016 18:12:31 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>616.4297</td></tr><tr><td>Build</td><td>372</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Antlam 📱 6S</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>72% Unplugged</td></tr><tr><td>Memory free</td><td>135 MB / 1756 MB</td></tr><tr><td>Disk free</td><td>8624 MB / 56428 MB</td></tr><tr><td>Network IP</td><td>10.244.35.11</td></tr></table>

 [Link to buddybuild feedback from build 372](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5835dc0f1804830100754957&bnum=372)

**Comment by antlam** [comment]
![screen shot 2016-11-24 at 2 06 52 pm](https://cloud.githubusercontent.com/assets/1994820/20610487/561b2ed0-b24f-11e6-85b3-d1be528c28d9.png)

This should clear things up.
