### ISSUE TITLE
jmoradi@mozilla.com on build #407: Dulles. Surprised it didn't find Udvar Hazy museum. Then…

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#274]
Feedback from jmoradi@mozilla.com : Dulles. Surprised it didn't find Udvar Hazy museum. Then again, optimized for kona. 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/5837052f34ed490100aa6d47/db8bd49b-d147-42bd-a46b-08f2c948fdff.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Thu Nov 24 2016 17:04:52 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>84.37354</td></tr><tr><td>Build</td><td>407</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>iPhone</td></tr><tr><td>Screen size</td><td>320</td></tr><tr><td>Screen size</td><td>320px by 568px</td></tr><tr><td>Battery</td><td>73% Unplugged</td></tr><tr><td>Memory free</td><td>45 MB / 1737 MB</td></tr><tr><td>Disk free</td><td>4493 MB / 56382 MB</td></tr><tr><td>Network IP</td><td>10.124.115.26</td></tr></table>

 [Link to buddybuild feedback from build 407](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=58371db445e3f80100395a72&bnum=407)

**Comment by mcomella** [comment]
Not actionable.

@antlam FYI.
