### ISSUE TITLE
ricardo@mozilla.com on build #407: Header placed incorrectly in Map View

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#277]
Feedback from ricardo@mozilla.com : Header placed incorrectly in Map View

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/5837052f34ed490100aa6d47/ee9f97ce-4428-4871-be49-d2f2d11b4fbf.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Thu Nov 24 2016 19:08:43 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>580.099</td></tr><tr><td>Build</td><td>407</td></tr><tr><td>Device type</td><td>iPhone 6 Plus</td></tr><tr><td>Device name</td><td>Six</td></tr><tr><td>Screen size</td><td>414</td></tr><tr><td>Screen size</td><td>414px by 736px</td></tr><tr><td>Battery</td><td>77% Unplugged</td></tr><tr><td>Memory free</td><td>67 MB / 2927 MB</td></tr><tr><td>Disk free</td><td>18036 MB / 56170 MB</td></tr><tr><td>Network IP</td><td>0.0.0.0</td></tr></table>

 [Link to buddybuild feedback from build 407](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=58373abb7752b20100187533&bnum=407)

**Comment by vazquez** [comment]
![map](https://cloud.githubusercontent.com/assets/1119821/20608522/b7cab4c4-b250-11e6-8782-5037478aef7e.png)

**Comment by fluffyemily** [comment]
@vazquez I can't seem to replicate this. I cannot get my carousel view to look like the one in the original picture, and I am not sure what is incorrectly placed in the second image you posted. Can you please add details to clarify what is wrong here.

Here is what my master version looks like this morning:

<img width="321" alt="screen shot 2016-11-25 at 11 09 27" src="https://cloud.githubusercontent.com/assets/12613048/20623492/b726698c-b2ff-11e6-837a-aa35b45e4a41.png">

**Comment by vazquez** [comment]
I _think_ @sleroux already merged the fix to master. If so, @sleroux you can close this issue!

**Comment by sleroux** [comment]
https://github.com/mozilla-mobile/prox/pull/292
