### ISSUE TITLE
Unknown user on build #407: Shadow does not match spec

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#278]
Feedback from Unknown user : Shadow does not match spec

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/5837053234ed490100aa6d48/8389ee9d-4f33-4250-96d8-6750c61beca9.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Thu Nov 24 2016 19:09:16 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>626.6774</td></tr><tr><td>Build</td><td>407</td></tr><tr><td>Device type</td><td>iPhone 7</td></tr><tr><td>Device name</td><td>Antlam 7</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>60% Charging</td></tr><tr><td>Memory free</td><td>103 MB / 1649 MB</td></tr><tr><td>Disk free</td><td>76706 MB / 116301 MB</td></tr><tr><td>Network IP</td><td>10.244.29.98</td></tr></table>

 [Link to buddybuild feedback from build 407](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=58373adcee346b0100534961&bnum=407)

**Comment by antlam** [comment]
I am this "unknown user" - @vazquez to post spec

**Comment by vazquez** [comment]
![map](https://cloud.githubusercontent.com/assets/1119821/20608487/83d2abd6-b250-11e6-933b-c1129cbf30ed.png)

**Comment by sleroux** [comment]
https://github.com/mozilla-mobile/prox/pull/297
