### ISSUE TITLE
Unknown user on build #407: Center map icon

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#279]
Feedback from Unknown user : Center map icon

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/5837053234ed490100aa6d48/ce62e99d-1740-4ca8-be89-9393ece20491.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Thu Nov 24 2016 19:42:42 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>2632.588</td></tr><tr><td>Build</td><td>407</td></tr><tr><td>Device type</td><td>iPhone 7</td></tr><tr><td>Device name</td><td>Antlam's 📱 7</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>89% Charging</td></tr><tr><td>Memory free</td><td>67 MB / 1656 MB</td></tr><tr><td>Disk free</td><td>76683 MB / 116301 MB</td></tr><tr><td>Network IP</td><td>10.244.29.98</td></tr></table>

 [Link to buddybuild feedback from build 407](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=583742b2deffed01002928d3&bnum=407)

**Comment by sleroux** [comment]
https://github.com/mozilla-mobile/prox/pull/296
