### ISSUE TITLE
Unknown user on build #407: Next image is peeking through in the header

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#281]
Feedback from Unknown user : Next image is peeking through in the header

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/5837052f34ed490100aa6d47/40a3b1be-c55c-408c-873a-4c826083b153.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Thu Nov 24 2016 20:36:25 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>48.33005</td></tr><tr><td>Build</td><td>407</td></tr><tr><td>Device type</td><td>iPhone 7</td></tr><tr><td>Device name</td><td>Antlam's 📱 7</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>100% Unplugged</td></tr><tr><td>Memory free</td><td>224 MB / 1607 MB</td></tr><tr><td>Disk free</td><td>76627 MB / 116301 MB</td></tr><tr><td>Network IP</td><td>10.244.29.98</td></tr></table>

 [Link to buddybuild feedback from build 407](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=58374f495e98350100d728f4&bnum=407)

**Comment by sleroux** [comment]
https://github.com/mozilla-mobile/prox/pull/295
