### ISSUE TITLE
jmoradi@mozilla.com on build #407: Just landed at 7:30 pm 4 places. This one is still open,…

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#283]
Feedback from jmoradi@mozilla.com : Just landed at 7:30 pm 4 places. This one is still open, others are closed. (Helicopter tours was 1st

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/5837052f34ed490100aa6d47/90b50919-acf0-4c78-b20d-4f584d9272b4.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Fri Nov 25 2016 05:49:12 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>87.19487</td></tr><tr><td>Build</td><td>407</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>iPhone</td></tr><tr><td>Screen size</td><td>320</td></tr><tr><td>Screen size</td><td>320px by 568px</td></tr><tr><td>Battery</td><td>42% Unplugged</td></tr><tr><td>Memory free</td><td>157 MB / 1727 MB</td></tr><tr><td>Disk free</td><td>4165 MB / 56382 MB</td></tr><tr><td>Network IP</td><td>10.131.215.18</td></tr></table>

 [Link to buddybuild feedback from build 407](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5837d0d81806dd0100b1c571&bnum=407)

**Comment by mcomella** [comment]
@vazquez @antlam FYI.

If you want something more actionable, please file another bug.

**Comment by mcomella** [comment]
Maybe the issue was 4 places? But then #310 was filed so I think this is fine.
