### ISSUE TITLE
jmoradi@mozilla.com on build #407: Found my grocery store

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#284]
Feedback from jmoradi@mozilla.com : Found my grocery store 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/5837052f34ed490100aa6d47/4b652027-9eca-4836-9e09-ace057b93109.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Fri Nov 25 2016 07:44:46 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>5084.877</td></tr><tr><td>Build</td><td>407</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>iPhone</td></tr><tr><td>Screen size</td><td>320</td></tr><tr><td>Screen size</td><td>320px by 568px</td></tr><tr><td>Battery</td><td>24% Charging</td></tr><tr><td>Memory free</td><td>146 MB / 1787 MB</td></tr><tr><td>Disk free</td><td>4149 MB / 56382 MB</td></tr><tr><td>Network IP</td><td>10.131.215.18</td></tr></table>

 [Link to buddybuild feedback from build 407](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5837ebee91b7cb0100bf8d4e&bnum=407)

**Comment by mcomella** [comment]
Don't think there's anything to do here...
