### ISSUE TITLE
jmoradi@mozilla.com on build #407: Quite a few of the things around me are other hotels

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#285]
Feedback from jmoradi@mozilla.com : Quite a few of the things around me are other hotels 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/5837052f34ed490100aa6d47/ef93a67b-656c-4f2d-8cda-d9bf371571e9.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Fri Nov 25 2016 07:45:56 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>5155.908</td></tr><tr><td>Build</td><td>407</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>iPhone</td></tr><tr><td>Screen size</td><td>320</td></tr><tr><td>Screen size</td><td>320px by 568px</td></tr><tr><td>Battery</td><td>25% Charging</td></tr><tr><td>Memory free</td><td>94 MB / 1792 MB</td></tr><tr><td>Disk free</td><td>4154 MB / 56382 MB</td></tr><tr><td>Network IP</td><td>10.131.215.18</td></tr></table>

 [Link to buddybuild feedback from build 407](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5837ec34554ac00100f0e495&bnum=407)

**Comment by mcomella** [comment]
@vazquez @antlam FYI.

**Comment by mcomella** [comment]
We removed hotels in Kona.
