### ISSUE TITLE
Open Reviews and Descriptions by Default

### ISSUE THREAD

**Issue by fluffyemily** [mozilla-mobile/prox#286]
Currently reviews and descriptions are closed by default, until the user opens them. They should default to open until the user closes them

**Comment by fluffyemily** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Polish: As a user, I want to see the Yelp Top Review, Wikipedia Summary open by default on the Home Card view](https://trello.com/c/GUa4CFyx/216-polish-as-a-user-i-want-to-see-the-yelp-top-review-wikipedia-summary-open-by-default-on-the-home-card-view)

**Comment by mcomella** [comment]
#119 is a more complicated version of this.

@fluffyemily Suggestion: if we do this, perhaps we want to put the Wikipedia summaries on top of the Yelp reviews. Wikipedia is less common and since users will have to scroll to see it, they'll never think it's there.

**Comment by fluffyemily** [comment]
@mcomella  the wikipedia description view is already on top of the yelp reviews

**Comment by antlam** [comment]
Having these expanded by default is an awkward UX solution. It's also not something we want in the long run (having collapsible views expanded by default). 

Is it possible to work towards issue #119 instead?

**Comment by fluffyemily** [comment]
@antlam given the current data we gather from our sources, we do not have the capbility to provide reviewer details.

What we can do is open the first description view by default and keep the others closed until requested. Right now, it is looking like we are only going to have Yelp reviews anyway as I haven't seen a wikipedia entry for weeks now and trip advisor is also noticeably absent

**Comment by fluffyemily** [comment]
also, to include the Trip Advisor Highlight from #119 we will need a Trip Advisor small logo

**Comment by antlam** [comment]
<img width="862" alt="screen shot 2016-11-28 at 9 24 04 am" src="https://cloud.githubusercontent.com/assets/1994820/20678770/dcb19aba-b54c-11e6-81b2-e02bdf5b482e.png">

[logo_TA_small.zip](https://github.com/mozilla-mobile/prox/files/616973/logo_TA_small.zip)

**Comment by fluffyemily** [comment]
@antlam quick UI review?

<img width="378" alt="screen shot 2016-11-28 at 17 55 15" src="https://cloud.githubusercontent.com/assets/12613048/20679706/ef3a39c0-b593-11e6-9bcb-63667aa7036c.png">

**Comment by antlam** [comment]
👍
