### ISSUE TITLE
Fix rounded corner/image overlap during transition animation

### ISSUE THREAD

**Issue by sleroux** [mozilla-mobile/prox#294]
Talked to @antlam @vazquez yesterday and there are a couple of issues with the current animation that need smoothing out.

1.  When transitioning from/to the detail view, the cell's image is rounded on all 4 corners when the animation begins and ends. It should only be rounded on the top two corners
2. When transitioning away from the detail, there is a slight overlap of the carousel image with the current place card.
3. When on the nth card and the user transitions back, the carousel should unwind to the first image

**Comment by mcomella** [comment]
We don't have a place carousel anymore.
