### ISSUE TITLE
Consistent 1px horizontal dividers in the UI

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/prox#300]
@vazquez and myself looked through and realized we have our dividers set at 23% opacity for some reason.

I just wanted to clean up these numbers and be sure they're all set at 1px, #CCCCCC, at **30%.**

**Comment by mcomella** [comment]
@antlam Which dividers does this refer to? I see the ones between Yelp Top Review/Wikipedia summary and on map view, below "# places".

**Comment by mcomella** [comment]
> Which dividers does this refer to?

It refers to map view in #302.

**Comment by mcomella** [comment]
I did the ones I mentioned in the previous comment. Please tell me if there are more to do.
