### ISSUE TITLE
alam@mozilla.com on build #463: Unify divider colour to be #CCCCCC

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#302]
Feedback from alam@mozilla.com : Unify divider colour to be #CCCCCC

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/583865f56d4743010090e29a/c7db7f89-8692-4dc3-a51b-fb4c9ec22126.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Fri Nov 25 2016 18:24:24 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>25.00513</td></tr><tr><td>Build</td><td>463</td></tr><tr><td>Device type</td><td>iPhone 7</td></tr><tr><td>Device name</td><td>Antlam's 📱 7</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>73% Unplugged</td></tr><tr><td>Memory free</td><td>49 MB / 1690 MB</td></tr><tr><td>Disk free</td><td>75926 MB / 116301 MB</td></tr><tr><td>Network IP</td><td>10.244.29.98</td></tr></table>

 [Link to buddybuild feedback from build 463](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=583881d87c32f101006c842d&bnum=463)

**Comment by mcomella** [comment]
Dupe #300.

![7pq19o](https://cloud.githubusercontent.com/assets/759372/20692756/d9f97be8-b58e-11e6-8108-2cfe20db9996.jpeg)
