### ISSUE TITLE
alam@mozilla.com on build #463: Active shadow should be fixed on whatever card is in this…

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#305]
Feedback from alam@mozilla.com : Active shadow should be fixed on whatever card is in this position 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/583865f56d4743010090e29a/f3d5c7a6-7b94-42c1-9bbb-dbc5fd7673a5.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Fri Nov 25 2016 21:14:54 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>31.25642</td></tr><tr><td>Build</td><td>463</td></tr><tr><td>Device type</td><td>iPhone 7</td></tr><tr><td>Device name</td><td>Antlam's 📱 7</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>94% Charging</td></tr><tr><td>Memory free</td><td>73 MB / 1765 MB</td></tr><tr><td>Disk free</td><td>75722 MB / 116301 MB</td></tr><tr><td>Network IP</td><td>0.0.0.0</td></tr></table>

 [Link to buddybuild feedback from build 463](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5838a9ce99f45c0100e4c77f&bnum=463)

**Comment by antlam** [comment]
@sleroux this is just what we were talking about. Filing to keep track :)

**Comment by sleroux** [comment]
https://github.com/mozilla-mobile/prox/pull/315
