### ISSUE TITLE
alam@mozilla.com on build #472: Copy update: "The latest from Yelp" and "The top line from…

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#307]
Feedback from alam@mozilla.com : Copy update: "The latest from Yelp" and "The top line from Wikipedia" 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58388d882242fb010022a8ac/15eebfa5-3782-4490-8d01-e62026706fa3.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Fri Nov 25 2016 22:11:09 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>77.49404</td></tr><tr><td>Build</td><td>472</td></tr><tr><td>Device type</td><td>iPhone 7</td></tr><tr><td>Device name</td><td>Antlam's 📱 7</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>100% Full</td></tr><tr><td>Memory free</td><td>470 MB / 1666 MB</td></tr><tr><td>Disk free</td><td>75703 MB / 116301 MB</td></tr><tr><td>Network IP</td><td>0.0.0.0</td></tr></table>

 [Link to buddybuild feedback from build 472](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5838b6fd99f45c0100e4c95e&bnum=472)

**Comment by mcomella** [comment]
@fluffyemily Please also specify, "Highlights from TripAdvisor" (from #320).
