### ISSUE TITLE
jmoradi@mozilla.com on build #472: Note There's a big delay if you leave the area (I'm in…

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#309]
Feedback from jmoradi@mozilla.com : Note There's a big delay if you leave the area (I'm in another town) also, I haven't seen notifications yet for Waikoloa 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58388d882242fb010022a8ac/c4d48dcc-b5cb-425c-a1d7-7cb025d7c296.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Sat Nov 26 2016 21:00:46 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>542.6447</td></tr><tr><td>Build</td><td>472</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>iPhone</td></tr><tr><td>Screen size</td><td>320</td></tr><tr><td>Screen size</td><td>320px by 568px</td></tr><tr><td>Battery</td><td>54% Unplugged</td></tr><tr><td>Memory free</td><td>97 MB / 1719 MB</td></tr><tr><td>Disk free</td><td>3915 MB / 56382 MB</td></tr><tr><td>Network IP</td><td>10.74.79.33</td></tr></table>

 [Link to buddybuild feedback from build 472](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5839f7fea166b20100a7aaa9&bnum=472)

**Comment by mcomella** [comment]
Known issue - not planning to fix for Hawaii.
