### ISSUE TITLE
jmoradi@mozilla.com on build #472: Re my last bug report it finally updated

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#310]
Feedback from jmoradi@mozilla.com : Re my last bug report it finally updated

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58388d882242fb010022a8ac/c3460144-de8b-4f98-b2a2-dbd5f7d13845.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Sat Nov 26 2016 21:01:21 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>576.5244</td></tr><tr><td>Build</td><td>472</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>iPhone</td></tr><tr><td>Screen size</td><td>320</td></tr><tr><td>Screen size</td><td>320px by 568px</td></tr><tr><td>Battery</td><td>54% Unplugged</td></tr><tr><td>Memory free</td><td>60 MB / 1727 MB</td></tr><tr><td>Disk free</td><td>3913 MB / 56382 MB</td></tr><tr><td>Network IP</td><td>10.74.79.33</td></tr></table>

 [Link to buddybuild feedback from build 472](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5839f821a166b20100a7aaac&bnum=472)

**Comment by mcomella** [comment]
I think old bug report was ^.

Nothing actionable here.
