### ISSUE TITLE
etoop@mozilla.com on build #472: After 3 retries to find new places, the pulse stopped…

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#312]
Feedback from etoop@mozilla.com : After 3 retries to find new places, the pulse stopped pulsing. 

The was after pressing search again after being brought from the background. 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58388d882242fb010022a8ac/afd6a16d-a262-474d-807b-b76bd192df45.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Sun Nov 27 2016 12:38:31 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>400.8338</td></tr><tr><td>Build</td><td>472</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Emily's iPhone 6S</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>80% Unplugged</td></tr><tr><td>Memory free</td><td>27 MB / 1799 MB</td></tr><tr><td>Disk free</td><td>14849 MB / 56363 MB</td></tr><tr><td>Network IP</td><td>10.141.32.6</td></tr></table>

 [Link to buddybuild feedback from build 472](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=583ad3c799f45c0100e4e5b7&bnum=472)

**Comment by sleroux** [comment]
https://github.com/mozilla-mobile/prox/pull/364
