### ISSUE TITLE
alam@mozilla.com on build #484: Spacing around Yelp info is incorrect

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#318]
Feedback from alam@mozilla.com : Spacing around Yelp info is incorrect

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/583c0eaefc26cf010072ad21/0dac8b30-56ca-4eda-aeec-91569ea51cf8.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Mon Nov 28 2016 19:23:45 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>118.9225</td></tr><tr><td>Build</td><td>484</td></tr><tr><td>Device type</td><td>iPhone 7</td></tr><tr><td>Device name</td><td>Antlam's 📱 7</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>100% Charging</td></tr><tr><td>Memory free</td><td>109 MB / 1802 MB</td></tr><tr><td>Disk free</td><td>74636 MB / 116301 MB</td></tr><tr><td>Network IP</td><td>10.244.37.172</td></tr></table>

 [Link to buddybuild feedback from build 484](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=583c844177ec820100049db1&bnum=484)

**Comment by mcomella** [comment]
As you swipe through cards, the spacing appears to change. Perhaps we're accidentally incrementing the spacing (or, if we didn't disable it as I thought we did, card re-use is causing problems).

**Comment by antlam** [comment]
In the previous spec, the padding on the left and right of the content here "The food here is really good..." (in the screenshot above) was set at 16px. We'd like to increase this to 24px to match the title of the location.

@mcomella can we add that to this issue since this is about fixing the padding in general?

**Comment by mcomella** [comment]
> @mcomella can we add that to this issue since this is about fixing the padding in general?

Done.
