### ISSUE TITLE
alam@mozilla.com on build #484: Empty TA section expanded

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#319]
Feedback from alam@mozilla.com : Empty TA section expanded

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/583c0eaefc26cf010072ad21/8fc7e783-093e-484d-a2dd-956698767bfa.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Mon Nov 28 2016 19:24:21 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>153.4953</td></tr><tr><td>Build</td><td>484</td></tr><tr><td>Device type</td><td>iPhone 7</td></tr><tr><td>Device name</td><td>Antlam's 📱 7</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>100% Charging</td></tr><tr><td>Memory free</td><td>64 MB / 1805 MB</td></tr><tr><td>Disk free</td><td>74634 MB / 116301 MB</td></tr><tr><td>Network IP</td><td>10.244.37.172</td></tr></table>

 [Link to buddybuild feedback from build 484](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=583c84654999990100047304&bnum=484)

**Comment by mcomella** [comment]
Dupe #329.
