### ISSUE TITLE
alam@mozilla.com on build #484:  Copy update: Highlights from TripAdvisor

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#320]
Feedback from alam@mozilla.com :  Copy update: Highlights from TripAdvisor 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/583c0eaefc26cf010072ad21/1f54f7c8-676e-4c70-b826-b55e4c47a252.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Mon Nov 28 2016 19:46:40 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>32.46431</td></tr><tr><td>Build</td><td>484</td></tr><tr><td>Device type</td><td>iPhone 7</td></tr><tr><td>Device name</td><td>Antlam's 📱 7</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>100% Full</td></tr><tr><td>Memory free</td><td>90 MB / 1812 MB</td></tr><tr><td>Disk free</td><td>74629 MB / 116301 MB</td></tr><tr><td>Network IP</td><td>10.244.37.172</td></tr></table>

 [Link to buddybuild feedback from build 484](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=583c89a0b5ee3f0100ab4455&bnum=484)

**Comment by antlam** [comment]
@fluffyemily related to issue #307 - here's the update for TA! :)

**Comment by mcomella** [comment]
Closing in favor of #307.
