### ISSUE TITLE
jmoradi@mozilla.com on build #472: Update not bug. 20 cards at Hilton Waikoloa. At least 3/4…

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#323]
Feedback from jmoradi@mozilla.com : Update not bug. 20 cards at Hilton Waikoloa. At least 3/4 are driving places not walking. Most are what  to what we see at our condo (1/2 mile away). Mix of restaurants and outdoor tours, grocery, and a photographer. I don't have a need at the moment (heading to  pool/lagoon) but will check again when we get hungry. 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58388d882242fb010022a8ac/f11bd548-427f-45ad-8a99-d85b047692dc.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Mon Nov 28 2016 21:02:51 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>8996.822</td></tr><tr><td>Build</td><td>472</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>iPhone</td></tr><tr><td>Screen size</td><td>320</td></tr><tr><td>Screen size</td><td>320px by 568px</td></tr><tr><td>Battery</td><td>71% Unplugged</td></tr><tr><td>Memory free</td><td>207 MB / 1522 MB</td></tr><tr><td>Disk free</td><td>3556 MB / 56382 MB</td></tr><tr><td>Network IP</td><td>10.20.3.78</td></tr></table>

 [Link to buddybuild feedback from build 472](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=583c9b7bc75dd601008d5e24&bnum=472)

**Comment by mcomella** [comment]
UX is adjusting this all the time.

@antlam @vazquez FYI. I'm going to close this.
