### ISSUE TITLE
Updated copy for Card View Error State

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/prox#324]
![screen shot 2016-11-28 at 1 13 46 pm](https://cloud.githubusercontent.com/assets/1994820/20686229/b1b334e8-b56c-11e6-8d0b-01723b24ea2b.png)

We'll use the same styles as the second line (regular, 14, 50% black) for the entire string.

**Comment by antlam** [comment]
![screen shot 2016-11-29 at 9 09 21 am](https://cloud.githubusercontent.com/assets/1994820/20720338/9a6c56aa-b613-11e6-963b-d75451522168.png)

Update from Michelle - "No info available" instead of "No data" here.

**Comment by antlam** [comment]
@mcomella is this possible to get in for Kona?

**Comment by mcomella** [comment]
> @mcomella is this possible to get in for Kona?

I don't know – please prioritize with the other bugs.

**Comment by mcomella** [comment]
Must be done EOD because it can cause regressions.

**Comment by mcomella** [comment]
> Update from Michelle - "No info available" instead of "No data" here.

Filed #369.

**Comment by mcomella** [comment]
SE result:

![simulator screen shot dec 2 2016 16 29 42](https://cloud.githubusercontent.com/assets/759372/20855434/bd5c42f6-b8b1-11e6-8381-fc05cf1ac41a.png)
