### ISSUE TITLE
jmoradi@mozilla.com on build #472: It's pretty darn good at waikoloa Hilton! First result is…

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#334]
Feedback from jmoradi@mozilla.com : It's pretty darn good at waikoloa Hilton! First result is "Hilton" even though I'm there. But most results are good and entertainment and most walkable. I noticed that many at the end say "travel time unknown" and I think some of these are on the grounds. 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58388d882242fb010022a8ac/7e6088d1-b52b-4ca7-90ed-404ff4159957.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Tue Nov 29 2016 04:16:05 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>175.4408</td></tr><tr><td>Build</td><td>472</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>iPhone</td></tr><tr><td>Screen size</td><td>320</td></tr><tr><td>Screen size</td><td>320px by 568px</td></tr><tr><td>Battery</td><td>19% Unplugged</td></tr><tr><td>Memory free</td><td>81 MB / 1443 MB</td></tr><tr><td>Disk free</td><td>3096 MB / 56382 MB</td></tr><tr><td>Network IP</td><td>10.128.18.170</td></tr></table>

 [Link to buddybuild feedback from build 472](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=583d010596ac2001002dd10d&bnum=472)

**Comment by mcomella** [comment]
@antlam @vazquez FYI for results.

Dupe #358 for "Travel time unknown".
