### ISSUE TITLE
jmoradi@mozilla.com on build #472: Feature suggestion: the app says the sunrise time, but a…

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#336]
Feedback from jmoradi@mozilla.com : Feature suggestion: the app says the sunrise time, but a notification for sunset would be useful. The resort is on the west coast and sunsets are epic events. People start walking to viewing spots 30 min prior (sunset is around 5:40 pm each night). It's not to miss. At my resort there is an old man wrapped in a blue toga who blows a conch shell from about 15 min before sunset until the sun goes down and then everyone claps. Pretty sure he's paid to do it. You could hardcore to  notify at 5:10 every night and maybe have a snappy bit of copy for each night that people look forward to: "put down work. The sun is setting. Mahalo" (ask matej he's better than me ;-)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58388d882242fb010022a8ac/7c03f6a9-cd5a-4010-ac2e-a942b9847f9e.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Tue Nov 29 2016 05:09:20 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>3369.723</td></tr><tr><td>Build</td><td>472</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>iPhone</td></tr><tr><td>Screen size</td><td>320</td></tr><tr><td>Screen size</td><td>320px by 568px</td></tr><tr><td>Battery</td><td>49% Unplugged</td></tr><tr><td>Memory free</td><td>124 MB / 1608 MB</td></tr><tr><td>Disk free</td><td>3066 MB / 56382 MB</td></tr><tr><td>Network IP</td><td>192.168.1.44</td></tr></table>

 [Link to buddybuild feedback from build 472](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=583d0d80dfcd24010008c431&bnum=472)

**Comment by mcomella** [comment]
@liuche Can we add this to the custom calendar for a quick win?

If so, @antlam do we want to track for current sprint?

**Comment by liuche** [comment]
@mcomella yep, that was the plan! I'm not sure who is point for adding events like these, maybe Michelle? @antlam do you know if Michelle has copy for sunsets?

**Comment by mcomella** [comment]
We had the idea for sunrise/set notifications - probably don't need an issue for it anymore.
