### ISSUE TITLE
alam@mozilla.com on build #522: Missing reviews and ratings data

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#338]
Feedback from alam@mozilla.com : Missing reviews and ratings data 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/583db82efac401010076c7da/31433d21-9c48-4379-8abe-56e69435dbbf.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Tue Nov 29 2016 17:28:03 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>256.7281</td></tr><tr><td>Build</td><td>522</td></tr><tr><td>Device type</td><td>iPhone 7</td></tr><tr><td>Device name</td><td>Antlam's 📱 7</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>86% Unplugged</td></tr><tr><td>Memory free</td><td>66 MB / 1561 MB</td></tr><tr><td>Disk free</td><td>74275 MB / 116301 MB</td></tr><tr><td>Network IP</td><td>10.244.29.98</td></tr></table>

 [Link to buddybuild feedback from build 522](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=583dbaa300f8650100c85c0e&bnum=522)

**Comment by mcomella** [comment]
Fixed #345 .
