### ISSUE TITLE
mpopova@mozilla.com on build #522: Is this new - highlights from TA?

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#340]
Feedback from mpopova@mozilla.com : Is this new - highlights from TA?

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/583db82bfac401010076c7d9/1e3c86dd-9c7c-4533-95a2-dda4e3a364ef.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Tue Nov 29 2016 17:35:41 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>230.2869</td></tr><tr><td>Build</td><td>522</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Maria's iPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>80% Unplugged</td></tr><tr><td>Memory free</td><td>43 MB / 1715 MB</td></tr><tr><td>Disk free</td><td>778 MB / 11548 MB</td></tr><tr><td>Network IP</td><td>10.131.48.221</td></tr></table>

 [Link to buddybuild feedback from build 522](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=583dbc6d00f8650100c85c6c&bnum=522)

**Comment by mcomella** [comment]
Fixed #345.
