### ISSUE TITLE
Carousel annoyingly advances forward even after user interacted with it

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#342]
Feedback from mpopova@mozilla.com : When I manually swipe through pictures, sometimes the app will skip some and recent to previous pictures.  I

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/583db82efac401010076c7da/3bf10f9a-79f1-49a6-8593-8eaf7dfee0c8.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Tue Nov 29 2016 18:01:09 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>1742.505</td></tr><tr><td>Build</td><td>522</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Maria's iPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>78% Unplugged</td></tr><tr><td>Memory free</td><td>33 MB / 1632 MB</td></tr><tr><td>Disk free</td><td>796 MB / 11548 MB</td></tr><tr><td>Network IP</td><td>10.131.48.221</td></tr></table>

 [Link to buddybuild feedback from build 522](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=583dc26509a9ea010016e344&bnum=522)

**Comment by fluffyemily** [comment]
It appears that, occasionally, `touchesBegan` is not fired when a swipe begins on the `TouchableCollectionView`. I have not yet figured out why

**Comment by fluffyemily** [comment]
Further investigation shows that `touchesBegan` will not be called during the `setContentOffset` call on the `UIScrollView`, so if the user interaction with the carousel occurs at the same time as the autoscroll fires, then `touchesBegan` does not get called and autoscrolling is not stopped. I have no idea how to prevent this.
