### ISSUE TITLE
alam@mozilla.com on build #522: Rounded corners in images don't match container

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#343]
Feedback from alam@mozilla.com : Rounded corners in images don't match container

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/583db82efac401010076c7da/656cf99a-4e1c-4d60-8e19-7b83a962246f.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Tue Nov 29 2016 18:03:22 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>64.30796</td></tr><tr><td>Build</td><td>522</td></tr><tr><td>Device type</td><td>iPhone 7</td></tr><tr><td>Device name</td><td>Antlam's 📱 7</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>75% Unplugged</td></tr><tr><td>Memory free</td><td>371 MB / 1730 MB</td></tr><tr><td>Disk free</td><td>74282 MB / 116301 MB</td></tr><tr><td>Network IP</td><td>10.244.29.98</td></tr></table>

 [Link to buddybuild feedback from build 522](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=583dc2ea3adcc80100aff65b&bnum=522)

**Comment by mcomella** [comment]
Dupe #355.
