### ISSUE TITLE
mpopova@mozilla.com on build #529: I got to this card by tapping on a system notification.  The…

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#347]
Feedback from mpopova@mozilla.com : I got to this card by tapping on a system notification.  The event I was notified about is for a different place.  I understand Emily is working on this issue

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/583dc8c77017c20100bd23f2/e535bda9-dadc-4104-b983-2d6e11697e68.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Tue Nov 29 2016 19:51:16 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>737.2692</td></tr><tr><td>Build</td><td>529</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Maria's iPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>61% Unplugged</td></tr><tr><td>Memory free</td><td>40 MB / 1725 MB</td></tr><tr><td>Disk free</td><td>756 MB / 11548 MB</td></tr><tr><td>Network IP</td><td>10.131.48.221</td></tr></table>

 [Link to buddybuild feedback from build 529](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=583ddc3496c2a201000c2783&bnum=529)

**Comment by mcomella** [comment]
@fluffyemily Do you think this will be fixed by any of your patches?

Tracking this sprint so we don't lose it.

**Comment by fluffyemily** [comment]
@mcomella not sure. I'm surprised that with this build Maria was even able to respond successfully to a notification as that code didn't land until this morning.

**Comment by fluffyemily** [comment]
I suspect this is not related to #381

**Comment by fluffyemily** [comment]
Fixed with #381
