### ISSUE TITLE
'Uh oh' places messaging shown before loading in places on first load

### ISSUE THREAD

**Issue by sleroux** [mozilla-mobile/prox#351]
Build 529

Whenever starting the app from a cold boot, the loading screen is shown and the error messaging is animated in briefly before the places actually populate.
![error_mesaging](https://cloud.githubusercontent.com/assets/434322/20727412/624ba2f6-b647-11e6-8c2f-abb70374773f.gif)

**Comment by sleroux** [comment]
@jhugman Looks like this is caused by our delegate from `PlacesProvider.didError` since I show the error messaging when that is called. Looking at the code, it seems that this doesn't indicate an error fetching places but an error in telling the server to pre-fetch so we don't need to handle this I guess?

**Comment by sleroux** [comment]
https://github.com/mozilla-mobile/prox/pull/352

**Comment by antlam** [comment]
We should also just be opening in the Home/Card view rather than Map View.

**Comment by sleroux** [comment]
If we are going from loading state to card view directly, how would we transition between the two when we don't have the place card to anchor the animation from? Would we perform a different transition?

**Comment by sleroux** [comment]
Closing issue as the bug is fixed. We can open another issue for the animation.
