### ISSUE TITLE
[crash] pageToNextPlaceCard force unwraps nil in AppState.trackCardVisit

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/prox#353]
My checkout is 7501a2b1f046bc3e1a2d84fe79a0212fa64d6f67 in my branch, on top of the public commit 346835e822fbeb6e9aba0657ec9b5d09d0430d24.

My location is the SF office. In the line:
```swift
AppState.trackCardVisit(cardPos: (dataSource?.index(forPlace: nextCardViewController.place))!)`
```

`nextCardViewController.place` = "hello-nails-and-spa-vacaville"
`dataSource?.index(forPlace: nextCardViewController.place)` = nil

Which we forcibly try to unwrap. Surely enough, "hello-nails-and-spa-vacavile" is not in the places array:

![screen shot 2016-11-29 at 15 06 10](https://cloud.githubusercontent.com/assets/759372/20732851/77d1b6ee-b645-11e6-8a79-0d5ad0850236.png)

Some more debug info:
* `currentCardViewControllerPlace` = "49-square-tours-san-francisco", which is index 0.
* iirc, I opened the app and immediately began swiping right as fast as possible. It's strange that ^ was index 0.
* There is an event on the crashing card

Possible causes:
* (most likely) Something with how we insert places that have events
* We replaced the places array but didn't update previous/current/nextCardViewController

Here's a screenshot of the crash:
![img_20161129_144928](https://cloud.githubusercontent.com/assets/759372/20732714/d56d46c0-b644-11e6-9b39-cf523af7024a.jpg)

**Comment by liuche** [comment]
Closed by #375
