### ISSUE TITLE
alam@mozilla.com on build #529: Missing rounded corners on bottom

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#355]
Feedback from alam@mozilla.com : Missing rounded corners on bottom

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/583dc8ca7017c20100bd23f4/56fc1c3b-f945-4c25-b3ea-9c93e3ea75ca.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Tue Nov 29 2016 23:59:22 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>53.98073</td></tr><tr><td>Build</td><td>529</td></tr><tr><td>Device type</td><td>iPhone 7</td></tr><tr><td>Device name</td><td>Antlam's 📱 7</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>60% Charging</td></tr><tr><td>Memory free</td><td>44 MB / 1609 MB</td></tr><tr><td>Disk free</td><td>74203 MB / 116301 MB</td></tr><tr><td>Network IP</td><td>0.0.0.0</td></tr></table>

 [Link to buddybuild feedback from build 529](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=583e165ab46a8901002e842b&bnum=529)

**Comment by mcomella** [comment]
Note that this is top and bottom.

**Comment by antlam** [comment]
Looking closer, it's also in the top corners
