### ISSUE TITLE
alam@mozilla.com on build #529: Bottom isn't at 16 px padding

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#356]
Feedback from alam@mozilla.com : Bottom isn't at 16 px padding 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/583dc8ca7017c20100bd23f4/7757558d-0fdd-421d-8b47-e9115e0c2968.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Nov 30 2016 00:04:44 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>376.5229</td></tr><tr><td>Build</td><td>529</td></tr><tr><td>Device type</td><td>iPhone 7</td></tr><tr><td>Device name</td><td>Antlam's 📱 7</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>65% Charging</td></tr><tr><td>Memory free</td><td>146 MB / 1510 MB</td></tr><tr><td>Disk free</td><td>74160 MB / 116301 MB</td></tr><tr><td>Network IP</td><td>0.0.0.0</td></tr></table>

 [Link to buddybuild feedback from build 529](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=583e179c9a5a8601009ca86c&bnum=529)

**Comment by mcomella** [comment]
I think I fixed this in ^. Here's a post patch screenshot:

![simulator screen shot nov 30 2016 18 45 53](https://cloud.githubusercontent.com/assets/759372/20780065/59fa085e-b72d-11e6-94fd-63801e85dc6e.png)

**Comment by mcomella** [comment]
Merged #379.
