### ISSUE TITLE
mpopova@mozilla.com on build #539: Do I need to wait to update new location?

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#362]
Feedback from mpopova@mozilla.com : Do I need to wait to update new location?

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/583ec2d9f1877701005bf3fe/7cc88c07-283e-494d-a965-a680630e26df.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Nov 30 2016 14:51:25 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>220.4247</td></tr><tr><td>Build</td><td>539</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Maria's iPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>100% Unplugged</td></tr><tr><td>Memory free</td><td>29 MB / 1749 MB</td></tr><tr><td>Disk free</td><td>946 MB / 11548 MB</td></tr><tr><td>Network IP</td><td>10.127.32.254</td></tr></table>

 [Link to buddybuild feedback from build 539](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=583ee76de7222c0100724ab5&bnum=539)

**Comment by mcomella** [comment]
Dupe #363.
