### ISSUE TITLE
mpopova@mozilla.com on build #539: Don't seem to find any places near me (I am switching…

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#363]
Feedback from mpopova@mozilla.com : Don't seem to find any places near me (I am switching locations) in latest build

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/583ec2d9f1877701005bf3fe/fdc86bb8-14a9-4f19-9606-625e947730e3.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Nov 30 2016 15:00:05 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>740.519</td></tr><tr><td>Build</td><td>539</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Maria's iPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>98% Unplugged</td></tr><tr><td>Memory free</td><td>101 MB / 1785 MB</td></tr><tr><td>Disk free</td><td>995 MB / 11548 MB</td></tr><tr><td>Network IP</td><td>10.127.32.254</td></tr></table>

 [Link to buddybuild feedback from build 539](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=583ee975c77e1c0100f5dc81&bnum=539)

**Comment by mcomella** [comment]
@jhugman Is this just because Maria hasn't waited long enough in the new location?

**Comment by mcomella** [comment]
See https://trello.com/c/SBJq85xG/354-prox-not-showing-places-even-through-there-are-things-near-me
