### ISSUE TITLE
mpopova@mozilla.com on build #548: Clicking on More Info crashes the app

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#367]
Feedback from mpopova@mozilla.com : Clicking on More Info crashes the app

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/583ef208f1877701005bf56a/56109d6b-8925-4b3b-8250-bfd667bd36d0.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Nov 30 2016 18:05:24 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>1524.588</td></tr><tr><td>Build</td><td>548</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Maria's iPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>95% Charging</td></tr><tr><td>Memory free</td><td>111 MB / 1830 MB</td></tr><tr><td>Disk free</td><td>940 MB / 11548 MB</td></tr><tr><td>Network IP</td><td>10.131.48.52</td></tr></table>

 [Link to buddybuild feedback from build 548](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=583f14e4bbcd4a01004d0025&bnum=548)

**Comment by liuche** [comment]
I took a look at the Firebase for Flatiron and there is a link present and it seems to be valid.

**Comment by fluffyemily** [comment]
This crash seems related to https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/crashreport/40de0ae8b7161a782f6a9c5ae47b5ed9 rather than the MoreInfo button. This was the only crash reported on Build 548
