### ISSUE TITLE
mpopova@mozilla.com on build #553: Half of the places are quite far from my location and don't…

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#370]
Feedback from mpopova@mozilla.com : Half of the places are quite far from my location and don't show walking/driving time

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/583f131861760e010096484f/90327358-3a26-4b5d-8ef6-1a050459a232.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Nov 30 2016 18:23:28 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>97.12114</td></tr><tr><td>Build</td><td>553</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Maria's iPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>97% Charging</td></tr><tr><td>Memory free</td><td>32 MB / 1777 MB</td></tr><tr><td>Disk free</td><td>941 MB / 11548 MB</td></tr><tr><td>Network IP</td><td>10.131.48.52</td></tr></table>

 [Link to buddybuild feedback from build 553](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=583f19208cac09010038fe2c&bnum=553)

**Comment by mcomella** [comment]
* Travel times are rate-limited by Apple. We can be smarter about when a user may just scroll past a card (so don't get the time) or getting only walking/driving times if the place is obviously close/far. However, this is out of scope for Hawaii.
* We limit queries to 1km so I don't know what "quite far" is in this instance – i.e. is it a bug (bigger than 1km?)? Did iOS track the wrong location?

I don't think this is actionable without more information.

**Comment by mcomella** [comment]
Maria believes we fixed this with a later build.
