### ISSUE TITLE
alam@mozilla.com on build #553: Peek left card by 16px

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#371]
Feedback from alam@mozilla.com : Peek left card by 16px

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/583f131b61760e0100964850/ddf1cd8f-5f03-4bac-8b34-2da708588dca.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Nov 30 2016 19:09:56 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>91.25034</td></tr><tr><td>Build</td><td>553</td></tr><tr><td>Device type</td><td>iPhone 7</td></tr><tr><td>Device name</td><td>Antlam's 📱 7</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>56% Unplugged</td></tr><tr><td>Memory free</td><td>151 MB / 1724 MB</td></tr><tr><td>Disk free</td><td>73878 MB / 116301 MB</td></tr><tr><td>Network IP</td><td>10.244.29.98</td></tr></table>

 [Link to buddybuild feedback from build 553](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=583f2404e8c7300100674e87&bnum=553)

**Comment by sleroux** [comment]
https://github.com/mozilla-mobile/prox/pull/407
