### ISSUE TITLE
Problems with GCal Place discovery

### ISSUE THREAD

**Issue by fluffyemily** [mozilla-mobile/prox#381]
I created a bunch of gCal events on the custom calendar and not all of the places were well found

Lunchtime at[ Flat Iron Square](https://www.google.co.uk/maps/place/Flat+Iron+Square/@51.5041464,-0.0973454,17z/data=!4m5!3m4!1s0x487604a7e12c088d:0x2c8d441d8a84f441!8m2!3d51.5041464!4d-0.0951567) was located a the [Houses of Parliament](https://www.google.co.uk/maps/place/Houses+of+Parliament/@51.4997381,-0.1268353,17z/data=!3m1!4b1!4m5!3m4!1s0x47d8a1a484fc4097:0x4ac33b91e68a8cac!8m2!3d51.4997381!4d-0.1246466)

Bread Baking Classes at Borough Market was located at Borough Market

Free Jazz Concert at the Tate Modern was not in the database

Test Event at the Tower of London was located at the Doubletree Hotel at the Tower of London which is nearly right, but not quite

Another Test Event at Lord Nelson, 243 Union St, London SE1 0LR, UK was located at Spencers at the Waterfront, 1340 Lakeshore Rd, Burlington, ON L7S 1B1, Canada

1 out of 5 isn't great really

**Comment by jhugman** [comment]
Progress:

 * Flat Iron Square --> the-gentlemen-baristas-london
 * Borough Market --> la-tua-pasta-london-2
 * Tate Modern --> tate-modern-london
 * Tower of London --> tower-of-london-london-2
 * Lord Nelson --> lord-nelson-london-2

**Comment by liuche** [comment]
Should be fixed now by https://github.com/mozilla-mobile/prox-server/pull/68
