### ISSUE TITLE
mpopova@mozilla.com on build #553: Coming from a system notification, the app is hanging in…

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#384]
Feedback from mpopova@mozilla.com : Coming from a system notification, the app is hanging in this screen 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/583f131861760e010096484f/dd5e9486-59a8-4930-beae-af10002618b4.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Thu Dec 01 2016 15:15:30 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>313.0985</td></tr><tr><td>Build</td><td>553</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Maria's iPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>100% Unplugged</td></tr><tr><td>Memory free</td><td>104 MB / 1672 MB</td></tr><tr><td>Disk free</td><td>1018 MB / 11548 MB</td></tr><tr><td>Network IP</td><td>10.5.161.80</td></tr></table>

 [Link to buddybuild feedback from build 553](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=58403e92035c2501005010b3&bnum=553)

**Comment by fluffyemily** [comment]
This is a known issue and being addressed in #361
