### ISSUE TITLE
alam@mozilla.com on build #584: Vertically center loading animation

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#389]
Feedback from alam@mozilla.com : Vertically center loading animation

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/584070995253bc0100cd3a4b/3c3f4539-166f-4b89-bc1e-9fac541c6442.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Thu Dec 01 2016 19:50:42 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>16.49344</td></tr><tr><td>Build</td><td>584</td></tr><tr><td>Device type</td><td>iPhone 7</td></tr><tr><td>Device name</td><td>Antlam's 📱 7</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>59% Unplugged</td></tr><tr><td>Memory free</td><td>73 MB / 1560 MB</td></tr><tr><td>Disk free</td><td>73481 MB / 116301 MB</td></tr><tr><td>Network IP</td><td>0.0.0.0</td></tr></table>

 [Link to buddybuild feedback from build 584](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=58407f1223ee580100891ac5&bnum=584)

**Comment by mcomella** [comment]
@antlam This looks a little low to me, probably because of the time bar. What do you think?

![simulator screen shot dec 2 2016 8 31 13](https://cloud.githubusercontent.com/assets/759372/20846314/eb52cf92-b87d-11e6-8759-09d421550748.png)

**Comment by antlam** [comment]
@mcomella looks good!

**Comment by mcomella** [comment]
SE w/ error text:

![simulator screen shot dec 2 2016 15 41 51](https://cloud.githubusercontent.com/assets/759372/20854205/b5b966d8-b8a6-11e6-9b6a-aebb17003686.png)
