### ISSUE TITLE
alam@mozilla.com on build #588: Copy update: Until 12:00 AM

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#391]
Feedback from alam@mozilla.com : Copy update: Until 12:00 AM

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58407fd0576f500100125ac3/767b43ca-4aa9-4186-ade0-023672847bbf.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Thu Dec 01 2016 20:04:31 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>29.20855</td></tr><tr><td>Build</td><td>588</td></tr><tr><td>Device type</td><td>iPhone 7</td></tr><tr><td>Device name</td><td>Antlam's 📱 7</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>57% Unplugged</td></tr><tr><td>Memory free</td><td>85 MB / 1677 MB</td></tr><tr><td>Disk free</td><td>73473 MB / 116301 MB</td></tr><tr><td>Network IP</td><td>0.0.0.0</td></tr></table>

 [Link to buddybuild feedback from build 588](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5840824f034b71010061c726&bnum=588)

**Comment by mcomella** [comment]
To be clear, this is the new copy:

Open | Until X
Closed | Until X
Not sure | Closing time (without the error state copy update)
