### ISSUE TITLE
Prox stalls on loading screen (missing location?)

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#392]
Feedback from mheubusch@mozilla.com : Prox regular can't find any results near me. It had been able to in previous builds 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/584070965253bc0100cd3a4a/61e45cca-9ffb-46fb-9984-4cbc6de23b7d.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Thu Dec 01 2016 20:05:45 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>271.5659</td></tr><tr><td>Build</td><td>584</td></tr><tr><td>Device type</td><td>iPhone 7</td></tr><tr><td>Device name</td><td>Michelle's iPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>34% Unplugged</td></tr><tr><td>Memory free</td><td>51 MB / 1532 MB</td></tr><tr><td>Disk free</td><td>102532 MB / 116315 MB</td></tr><tr><td>Network IP</td><td>192.168.0.14</td></tr></table>

 [Link to buddybuild feedback from build 584](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=58408299035c250100501b9e&bnum=584)

**Comment by mcomella** [comment]
I wonder if they moved to a new location.

#406 is also stuck on the loading screen – related?

**Comment by fluffyemily** [comment]
Frozen, or just sitting there for 60 seconds while we poll? Wonder if the
pulse is animating

>

**Comment by sleroux** [comment]
Looking at the logs, this might be a remote config error:

```
2016-12-01 12:56:25.166 Prox[9379:3032278] [BuddyBuildSDK] checkVersion : got result {
    force = 0;
    "prompt_for_upgrade" = 0;
}
2016-12-01 12:56:26.588 Prox[9379] <Error> [Firebase/RemoteConfig][I-RCN000016] Failed with SQL: DELETE FROM main WHERE bundle_identifier = ? and namespace = ?.
2016-12-01 12:56:26.588 Prox[9379] <Error> [Firebase/RemoteConfig][I-RCN000015] Error message: authorization denied. Error code: 23.
2016-12-01 12:56:26.588 Prox[9379] <Error> [Firebase/RemoteConfig][I-RCN000016] Failed with SQL: INSERT INTO main (bundle_identifier, namespace, key, value) values (?, ?, ?, ?).
2016-12-01 12:56:26.588 Prox[9379] <Error> [Firebase/RemoteConfig][I-RCN000015] Error message: authorization denied. Error code: 23.
2016-12-01 12:56:26.589 Prox[9379] <Error> [Firebase/RemoteConfig][I-RCN000016] Failed with SQL: INSERT INTO main (bundle_identifier, namespace, key, value) values (?, ?, ?, ?).
2016-12-01 12:56:26.589 Prox[9379] <Error> [Firebase/RemoteConfig][I-RCN000015] Error message: authorization denied. Error code: 23.
```

**Comment by mcomella** [comment]
@jhugman Did we switch to using the production Firebase endpoint? Perhaps this is an old build.

**Comment by mcomella** [comment]
> Did we switch to using the production Firebase endpoint?

I don't see anything in BB.

> Perhaps this is an old build.

Yesterday's build, it looks like. Nothing suspicious, but I didn't look that closely.

**Comment by mcomella** [comment]
Spoke with eng: we may be getting poor locations because we're connected to wifi.

We should consider showing an error when we can't get location rather than the current behavior of doing nothing.

**Comment by mcomella** [comment]
See additional discussion in #406.

@vazquez See previous comment – we have one more error state for you!

![73612876](https://cloud.githubusercontent.com/assets/759372/20845938/2f316086-b87c-11e6-91e1-d0318fae27a4.jpeg)

I'm thinking something really simple (a toast? Are those simple on iOS?) so that we don't have to worry about it breaking.

CC @antlam if Ricardo doesn't have time.

**Comment by antlam** [comment]
> We should consider showing an error when we can't get location rather than the current behavior of doing nothing.

Why don't we just use a regular iOS dialog with a confirmation message?

**Comment by vazquez** [comment]
![home - tropics ale house copy 15](https://cloud.githubusercontent.com/assets/1119821/20848931/49c5369a-b8a2-11e6-9344-83fc3e352cf4.png)

**Comment by antlam** [comment]
If they close this but don't actually restart Prox. Will it re-prompt?

**Comment by mcomella** [comment]
> If they close this but don't actually restart Prox. Will it re-prompt?

In the simple solution (which is the one I'm implementing), no.
