### ISSUE TITLE
Should we be able to tap on the carousel indicators?

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/prox#397]
* Currently we are able to tap on the carousel image indicators to switch images
* The current hit boxes are not touch friendly
* Disabling interactions with the indicators likely will fix #396

@antlam Thoughts? Other option would be to make the touch boxes for the indicators larger.

**Comment by antlam** [comment]
Being able to tap them is secondary. The primary interaction we're looking for here is swiping and that's further embodied in issue #61. That's why the indicators are so small :)

On top of that, we want tapping to be reserved for enlarging images  (issue #162)

**Comment by kbrosnan** [comment]
What about the suggestion to disable interaction?

**Comment by antlam** [comment]
hmm... I guess I might have misunderstood you. Sorry!

Disabling which interaction exactly?

**Comment by kbrosnan** [comment]
You can click on an inactive carousel indicator to switch to that image.

**Comment by antlam** [comment]
Yeah maybe we should disable it for now if it'll will fix #396
