### ISSUE TITLE
Database schema design.

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/prox#4]
[Discussion document](https://docs.google.com/document/d/16wXoYC3oCy1FWjqqWJYJXZummQSK98mhug00w81Enow/edit). [Schema proposal](https://docs.google.com/document/d/1FpH5S6pMGh7_bjBnYL8zeoZobni3q6oZyRZ4XMMiKWA/edit#)

Pending a write up to agree on client/server communication.

**Comment by liuche** [comment]
Current state: client side to add dummy data into the database in the format it uses/needs, and server will match that format.

**Comment by mcomella** [comment]
Decided on a schema: https://github.com/mozilla-mobile/prox-server/blob/master/schema.md
