### ISSUE TITLE
mpopova@mozilla.com on build #597: Incorrect number of places

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#403]
Feedback from mpopova@mozilla.com : Incorrect number of places

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/5840c416576f500100125df6/bca1ae43-4ba8-42aa-8602-3574c8fb4596.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Fri Dec 02 2016 04:35:10 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>2561.854</td></tr><tr><td>Build</td><td>597</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Maria's iPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>51% Unplugged</td></tr><tr><td>Memory free</td><td>29 MB / 1714 MB</td></tr><tr><td>Disk free</td><td>779 MB / 11548 MB</td></tr><tr><td>Network IP</td><td>0.0.0.0</td></tr></table>

 [Link to buddybuild feedback from build 597](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5840f9fe205eb50100c1b0e1&bnum=597)

**Comment by fluffyemily** [comment]
This is displaying a single event, probably in response to an event notification.

This results in an interesting edge case. We can find no places near you, but you've responded to an event, so you can see a place. But the event card is not in the list of places, so it's reporting 0.

I'll add the event to the place list when we receive a notification. That way it will always report at least one and you can still see the event place when you return to the carousel.

**Comment by mcomella** [comment]
> I'll add the event to the place list when we receive a notification.

fwiw, I'm concerned how such a systemic change might introduce regressions – I haven't seen the patch but I'd say we hold off on Hawaii.
