### ISSUE TITLE
mpopova@mozilla.com on build #597: Tapping on TA resulted in an app crash

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#404]
Feedback from mpopova@mozilla.com : Tapping on TA resulted in an app crash

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/5840c419576f500100125df7/dcce9ec2-9f14-4030-a5b5-440e8d3f7007.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Fri Dec 02 2016 04:52:33 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>528.3113</td></tr><tr><td>Build</td><td>597</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Maria's iPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>49% Unplugged</td></tr><tr><td>Memory free</td><td>61 MB / 1625 MB</td></tr><tr><td>Disk free</td><td>811 MB / 11548 MB</td></tr><tr><td>Network IP</td><td>0.0.0.0</td></tr></table>

 [Link to buddybuild feedback from build 597](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5840fe11eb935601006cf579&bnum=597)

**Comment by fluffyemily** [comment]
This is concerning me. It appears that Maria is experiencing crashes that are not being reported via buddybuild.

**Comment by mcomella** [comment]
Suspicion: since Maria crashes when clicking on links out of the apps, it's possible Prox isn't crashing but the transition between apps or the app we're launching is crashing. Emily suggested it could be an old version of Firefox.

**Comment by mcomella** [comment]
Maria & Emily debugged and discovered 1) the browser appears to be crashing and 2) the browser was out-of-date. Maria has updated and I don't think has seen this again – reopen if we see it again.
