### ISSUE TITLE
alex@alexdavis.ca on build #601: Opened app for first time and it's frozen on this map view.

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#406]
Feedback from alex@alexdavis.ca : Opened app for first time and it's frozen on this map view. 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58418c041a93660100792ed4/9fe30391-c8ff-4072-8d6d-2ff293a23057.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Fri Dec 02 2016 15:32:13 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>141.8759</td></tr><tr><td>Build</td><td>601</td></tr><tr><td>Device type</td><td>iPhone 7 Plus</td></tr><tr><td>Device name</td><td>FRIDAY</td></tr><tr><td>Screen size</td><td>414</td></tr><tr><td>Screen size</td><td>414px by 736px</td></tr><tr><td>Battery</td><td>98% Unplugged</td></tr><tr><td>Memory free</td><td>261 MB / 2765 MB</td></tr><tr><td>Disk free</td><td>135234 MB / 237033 MB</td></tr><tr><td>Network IP</td><td>10.45.92.85</td></tr></table>

 [Link to buddybuild feedback from build 601](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=584193fd2b87e80100f63af4&bnum=601)

**Comment by mcomella** [comment]
I'm assuming we have no data or Alex is in a new location.

@sleroux I remember you changed the "search again" screen – does that still happen?

Maybe we should show a count on the screen or "Waiting" text or something.

**Comment by sleroux** [comment]
> @sleroux I remember you changed the "search again" screen – does that still happen?

It should eventually timeout after 60 retries (which is about 60 seconds). A question I have is if the location indicator is still pulsing or if it looks frozen.

> Maybe we should show a count on the screen or "Waiting" text or something.

@antlam I remember seeing a mock up somewhere with some text like 'Hold on, where finding what's near you' or something. Did you want to include that?

**Comment by mcomella** [comment]
> It should eventually timeout after 60 retries (which is about 60 seconds).

Since we cached the Kona data, we don't have to worry about Hawaii.

But for future reference, I'd probably close the app after 15 or 20 – perhaps we should be explicit and say "Wait 60 seconds"?

**Comment by antlam** [comment]
> @antlam I remember seeing a mock up somewhere with some text like 'Hold on, where finding what's near you' or something. Did you want to include that?

I think @vazquez removed that in favor of the animation to show that "work is happening". That way, when it shows up, it's also a lot more noticeable as a "you have to do something now" prompt.

**Comment by vazquez** [comment]
There is a bias in cognitive science called the Illusion of Control. The illusion of control is the tendency to believe that we can influence something over which we have absolutely no sway. We want to steer away from explicitly telling people "Wait 60 seconds", because this explicitness removes the illusion of control. People would then a) abandon or b) wait but become frustrated. Research also shows that people have a highly distorted view of time. Saying "wait 60 seconds" feels more like 2 minutes.

**Comment by antlam** [comment]
Agree ^ I think we should focus this issue around the fact that it doesn't advance beyond this screen. I.e. Prox isn't loading

**Comment by mcomella** [comment]
> I think we should focus this issue around the fact that it doesn't advance beyond this screen.

For ^, I'm going to dupe to #392.
