### ISSUE TITLE
alam@mozilla.com on build #607: Text jumps/resizes horizontally after entering map view

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#409]
Feedback from alam@mozilla.com : Text jumps/resizes horizontally after entering map view

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/584192ac7576500100e86628/d83d5fdb-cf6e-4cc8-b973-1305c6e8aeeb.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Fri Dec 02 2016 16:25:53 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>89.80617</td></tr><tr><td>Build</td><td>607</td></tr><tr><td>Device type</td><td>iPhone 7</td></tr><tr><td>Device name</td><td>Antlam's 📱 7</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>86% Unplugged</td></tr><tr><td>Memory free</td><td>70 MB / 1768 MB</td></tr><tr><td>Disk free</td><td>73445 MB / 116301 MB</td></tr><tr><td>Network IP</td><td>10.244.37.172</td></tr></table>

 [Link to buddybuild feedback from build 607](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5841a091fcc9550100da5527&bnum=607)

**Comment by mcomella** [comment]
Dupe #408 (too slow antlam!)
