### ISSUE TITLE
alam@mozilla.com on build #607: In Vancouver, retrying for the 5th time

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#410]
Feedback from alam@mozilla.com : In Vancouver, retrying for the 5th time

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/584192a87576500100e86625/4d657990-240c-4168-a5ad-93e19f462efc.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Fri Dec 02 2016 17:04:15 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>510.513</td></tr><tr><td>Build</td><td>607</td></tr><tr><td>Device type</td><td>iPhone 7</td></tr><tr><td>Device name</td><td>Antlam's 📱 7</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>83% Unplugged</td></tr><tr><td>Memory free</td><td>71 MB / 1774 MB</td></tr><tr><td>Disk free</td><td>73436 MB / 116301 MB</td></tr><tr><td>Network IP</td><td>10.244.37.172</td></tr></table>

 [Link to buddybuild feedback from build 607](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5841a98fe3ae5f0100b6706f&bnum=607)

**Comment by mcomella** [comment]
@antlam In the office? I wonder if we can't find location.

It should be more apparent #417.

**Comment by antlam** [comment]
Yep. I was in the office. 

Can't remember if I was on Wifi or not though.

**Comment by mcomella** [comment]
See https://trello.com/c/SBJq85xG/354-prox-not-showing-places-even-through-there-are-things-near-me
