### ISSUE TITLE
alam@mozilla.com on build #607: Partially getting an event?

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#412]
Feedback from alam@mozilla.com : Partially getting an event?

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/584192ac7576500100e86628/1b7984a5-51cb-4a12-809d-72e66d721401.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Fri Dec 02 2016 18:34:56 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>61.37107</td></tr><tr><td>Build</td><td>607</td></tr><tr><td>Device type</td><td>iPhone 7</td></tr><tr><td>Device name</td><td>Antlam's 📱 7</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>70% Unplugged</td></tr><tr><td>Memory free</td><td>164 MB / 1725 MB</td></tr><tr><td>Disk free</td><td>73419 MB / 116301 MB</td></tr><tr><td>Network IP</td><td>0.0.0.0</td></tr></table>

 [Link to buddybuild feedback from build 607](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5841bed0e3ae5f0100b6733f&bnum=607)

**Comment by mcomella** [comment]
I'm guessing the event is missing description text so the UI collapses (whitespace string?) – I wonder if that's on the server side?

**Comment by mcomella** [comment]
Let's reopen if we see again.
