### ISSUE TITLE
Distinguish between open hours error states

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/prox#420]
Currently, we don't distinguish between:
* Missing hours data
* Closed today and tomorrow

We should do that because it would change the users action incentives.

**Comment by mcomella** [comment]
We also don't do anything special for open 24hrs so it looks like "Open | Until 12:00 AM".

**Comment by brampitoyo** [comment]
For open 24hrs, we can show something like “Open | 24 hours”.

For closed today and tomorrow, we can say “Closed | Today”. But for future closing times, we may be able to display it separately. See issue #453.

For missing hours data, I think the issue has been fixed on #324? We’ll say “Check listing for hours”.

**Comment by antlam** [comment]
@mheubusch@mozilla.com to get her thoughts on this :)

**Comment by mheubusch** [comment]
So, IIUC, you are proposing that for place that closes for one or more consecutive days per week, once the opening time has passed (e.g., Open Until 10:00 pm) It displays Closed | Today until 12:01 am of the day it reopens, then reverts to the (e.g., Closed Until 9 am) message?  If so, I think that sounds good.  Also like the Open 24 hours -  do we need to define rules for a place that is 24 but not 24/7? Like an around-the-clock diner that closes every Monday?

**Comment by antlam** [comment]
> Currently, we don't distinguish between: Missing hours data + Closed today and tomorrow

@mcomella  to reset here... 

Can we do this? 
- Missing hours data -> Current error state, "Check listing for hours"
- Closed today and tomorrow -> New error state, "Closed | until Monday" (or whatever day of the week its open next).

**Comment by mcomella** [comment]
We no longer show cards that are open today or tomorrow so this is no longer an issue.

Also, fwiw, hard-coded discover data either has hours or will show "open 24hr".
