### ISSUE TITLE
tapping on an event does not launch details

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/prox#421]
I am not able to tap on the event to view details. iPhone 7 ProxEnterpriseKona build 607, 616, & 619

https://www.youtube.com/watch?v=IMJNgMtllsQ

**Comment by mcomella** [comment]
The URLs for the test events specified in the calendar are not prepended with "http://" and we don't handle the prepending ourselves (...why doesn't iOS...?).

Work-around: don't add things to the custom calendar without "http://"!

Since we're likely to break that, I'll try to implement something.
