### ISSUE TITLE
etoop@mozilla.com on build #622: First run in Hilton. No places found

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#424]
Feedback from etoop@mozilla.com : First run in Hilton. No places found

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58423cc4dc15fb0100b70220/be336d3c-8720-4ea9-add4-3e67213c133f.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Sun Dec 04 2016 10:02:20 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>60.20346</td></tr><tr><td>Build</td><td>622</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Emily's iPhone 6S</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>46% Unplugged</td></tr><tr><td>Memory free</td><td>102 MB / 1739 MB</td></tr><tr><td>Disk free</td><td>14423 MB / 56363 MB</td></tr><tr><td>Network IP</td><td>10.39.90.108</td></tr></table>

 [Link to buddybuild feedback from build 622](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5843e9acbe511001004e6184&bnum=622)

**Comment by mcomella** [comment]
@fluffyemily Are we still seeing this issue?
