### ISSUE TITLE
etoop@mozilla.com on build #622: I am sat at Dons & Tonis Pizza

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#425]
Feedback from etoop@mozilla.com : I am sat at Dons & Tonis Pizza

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58423cc4dc15fb0100b70220/95628520-0366-442b-984f-5a8a1a8d3cb4.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Sun Dec 04 2016 10:03:31 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>125.7609</td></tr><tr><td>Build</td><td>622</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Emily's iPhone 6S</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>46% Unplugged</td></tr><tr><td>Memory free</td><td>39 MB / 1738 MB</td></tr><tr><td>Disk free</td><td>14423 MB / 56363 MB</td></tr><tr><td>Network IP</td><td>10.39.90.108</td></tr></table>

 [Link to buddybuild feedback from build 622](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5843e9f33391be01008cab93&bnum=622)

**Comment by mcomella** [comment]
Dupe #433.
