### ISSUE TITLE
etoop@mozilla.com on build #622: No trip advisor ratings

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#426]
Feedback from etoop@mozilla.com : No trip advisor ratings

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58423cc4dc15fb0100b70220/1aa01243-d881-44fd-b1b7-4e3603cab8fa.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Sun Dec 04 2016 22:54:43 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>2226.752</td></tr><tr><td>Build</td><td>622</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Emily's iPhone 6S</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>61% Unplugged</td></tr><tr><td>Memory free</td><td>47 MB / 1735 MB</td></tr><tr><td>Disk free</td><td>14483 MB / 56363 MB</td></tr><tr><td>Network IP</td><td>10.21.12.232</td></tr></table>

 [Link to buddybuild feedback from build 622](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=58449eb3dfcbcd010000df41&bnum=622)

**Comment by mcomella** [comment]
@jhugman, I believe you fixed this before we distributed, right?

**Comment by mcomella** [comment]
I think this is fixed: reopen if it's still an issue.
