### ISSUE TITLE
(move to Trello?) Feature suggestion: save for later

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#430]
Feedback from rnewman@mozilla.com : How do I save these things for later? 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/5844adeba5ebd1010099fde4/2e91dbd7-f26f-43c9-9e54-c09a28e0e4ff.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Tue Dec 06 2016 07:16:53 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>100.8135</td></tr><tr><td>Build</td><td>627</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Richard's iPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>84% Unplugged</td></tr><tr><td>Memory free</td><td>146 MB / 1514 MB</td></tr><tr><td>Disk free</td><td>11960 MB / 56428 MB</td></tr><tr><td>Network IP</td><td>10.133.199.36</td></tr></table>

 [Link to buddybuild feedback from build 627](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=584665e505291401000b9674&bnum=627)

**Comment by mcomella** [comment]
@antlam @brampitoyo FYI. Probably not something we'll be working on soon (close & move to trello?)

**Comment by brampitoyo** [comment]
@mcomella Yeah. This sounds like a v2 or later feature. Let’s close and move to Trello.

I’ve opened a card for it. Feel free to change the title as necessary and close this issue.

https://trello.com/c/37i2Mpok/324-as-a-user-i-would-like-to-save-places-later-so-i-can-read-about-it-even-when-i-m-not-nearby

**Comment by antlam** [comment]
done.
