### ISSUE TITLE
Opening hours display incorrectly for open 24hrs (Closed | Until 0:00)

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#432]
Feedback from kcambridge@mozilla.com : Minor glitch: The closing time seems off (it's a little past 6am now).

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/5844adeba5ebd1010099fde4/4dc0f89a-4f84-47ea-baae-0cb1c74532dd.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Tue Dec 06 2016 16:14:50 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>248.931</td></tr><tr><td>Build</td><td>627</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Kit's iPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>100% Full</td></tr><tr><td>Memory free</td><td>76 MB / 1306 MB</td></tr><tr><td>Disk free</td><td>8738 MB / 56909 MB</td></tr><tr><td>Network IP</td><td>10.20.21.28</td></tr></table>

 [Link to buddybuild feedback from build 627](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5846e3fad53e0e010030314d&bnum=627)

**Comment by mcomella** [comment]
[The Hilton is open 24hrs](https://www.yelp.com/biz/hilton-waikoloa-village-waikoloa-2) and we're showing "Closed | Until 00:00"

**Comment by brampitoyo** [comment]
We should replace the text label to something like “Open | 24 hours’

**Comment by brampitoyo** [comment]
We can probably address this issue along with other error states related to open hours on #420.

**Comment by antlam** [comment]
Closing this to be resolved in issue #420
