### ISSUE TITLE
erose@mozilla.com on build #632: The 2-layer presentation confused me. Since this is what…

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#435]
Feedback from erose@mozilla.com : The 2-layer presentation confused me. Since this is what appeared when I first launched the app, I though perhaps the white round rect in the foreground was a popup. The fact that swiping on the background changed it without affecting the foreground confirmed that the foreground and background were unrelated. Only after much experimentation did I realize that the round rect was not something I could dismiss, and I finally understood that the background pics were related to the foreground content.

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58463322c8a7cf0100050695/ce76a25c-5692-44c4-943a-e28cd122fe06.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Tue Dec 06 2016 22:52:22 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>7330.795</td></tr><tr><td>Build</td><td>632</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>iPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>81% Unplugged</td></tr><tr><td>Memory free</td><td>27 MB / 1603 MB</td></tr><tr><td>Disk free</td><td>66259 MB / 116781 MB</td></tr><tr><td>Network IP</td><td>172.16.40.169</td></tr></table>

 [Link to buddybuild feedback from build 632](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=58474126f876060100238bbd&bnum=632)

**Comment by mcomella** [comment]
We closed this as non-actionable on Trello.
