### ISSUE TITLE
Suggestion: allow users to select other locations to find results for

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#441]
Feedback from samb@mozillafoundation.org : Scrolling though the places nearby is super helpful and intuitive. Would also be helpful if I could zoom out and choose another location to see what's near there (eg I'm going to Hilo next week and am wondering what's near there)

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58463322c8a7cf0100050695/06e95a53-d83c-4d12-9a10-16f95eb3108b.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Dec 07 2016 07:27:19 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>202.1252</td></tr><tr><td>Build</td><td>632</td></tr><tr><td>Device type</td><td>iPhone 5s</td></tr><tr><td>Device name</td><td>iPhone</td></tr><tr><td>Screen size</td><td>320</td></tr><tr><td>Screen size</td><td>320px by 568px</td></tr><tr><td>Battery</td><td>41% Unplugged</td></tr><tr><td>Memory free</td><td>62 MB / 3955 MB</td></tr><tr><td>Disk free</td><td>1271 MB / 11597 MB</td></tr><tr><td>Network IP</td><td>10.20.54.231</td></tr></table>

 [Link to buddybuild feedback from build 632](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5847b9d7fabfb701004ea559&bnum=632)

**Comment by mcomella** [comment]
See https://trello.com/c/HyDbnivK/218-v2-as-a-user-i-want-to-see-more-options-around-me-so-that-i-can-plan-my-day-accordingly.
