### ISSUE TITLE
Yelp data: Showing locations that are permanently closed

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#446]
Feedback from v.pomerleau@gmail.com : Showing locations that are permanently closed

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58463322c8a7cf0100050695/152aebdd-9668-4d61-95d7-5b054843c189.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Dec 07 2016 20:57:01 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>54.71064</td></tr><tr><td>Build</td><td>632</td></tr><tr><td>Device type</td><td>iPhone 6</td></tr><tr><td>Device name</td><td>Valerie's iPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>54% Unplugged</td></tr><tr><td>Memory free</td><td>56 MB / 2643 MB</td></tr><tr><td>Disk free</td><td>94874 MB / 116152 MB</td></tr><tr><td>Network IP</td><td>0.0.0.0</td></tr></table>

 [Link to buddybuild feedback from build 632](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5848779d0e597c0100c6f69a&bnum=632)

**Comment by mcomella** [comment]
I've seen Yelp places that change their name to "<name> PERMANENTLY CLOSED" – I'm not sure:
* if this is how Yelp handles closed places
* If there is another flag we need to check
* If Yelp removes closed places but users couldn't figure out how to remove this place so they renamed it instead

**Comment by mcomella** [comment]
See https://trello.com/c/BrkMhnlV/356-as-a-user-i-don-t-want-to-see-places-that-are-permanently-closed.
