### ISSUE TITLE
v.pomerleau@gmail.com on build #632: I can't get to a map view.

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#449]
Feedback from v.pomerleau@gmail.com : I can't get to a map view.

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58463322c8a7cf0100050695/55b560db-cffe-4246-b179-bd835ada777d.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Dec 07 2016 22:29:10 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>5582.665</td></tr><tr><td>Build</td><td>632</td></tr><tr><td>Device type</td><td>iPhone 6</td></tr><tr><td>Device name</td><td>Valerie's iPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>38% Unplugged</td></tr><tr><td>Memory free</td><td>58 MB / 2424 MB</td></tr><tr><td>Disk free</td><td>94851 MB / 116152 MB</td></tr><tr><td>Network IP</td><td>0.0.0.0</td></tr></table>

 [Link to buddybuild feedback from build 632](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=58488d363fcffd0100d26c3c&bnum=632)

**Comment by mcomella** [comment]
Dupe #447.
