### ISSUE TITLE
kcambridge@mozilla.com on build #627: It would be lovely if Prox could show cached data, or an…

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#451]
Feedback from kcambridge@mozilla.com : It would be lovely if Prox could show cached data, or an "FYI, you're offline" screen, when connectivity is poor.

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/5844adeba5ebd1010099fde4/428d8a13-a611-46a0-b39a-8be01decc31d.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Thu Dec 08 2016 02:42:24 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>63894.62</td></tr><tr><td>Build</td><td>627</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Kit's iPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>71% Unplugged</td></tr><tr><td>Memory free</td><td>140 MB / 1709 MB</td></tr><tr><td>Disk free</td><td>8709 MB / 56909 MB</td></tr><tr><td>Network IP</td><td>172.16.158.47</td></tr></table>

 [Link to buddybuild feedback from build 627](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5848c89075e5040100f9a0ac&bnum=627)

**Comment by brampitoyo** [comment]
This issue is going to be addressed by #253.

**Comment by mcomella** [comment]
Or #365.
