### ISSUE TITLE
chsiang@mozilla.com on build #627: Can't find location

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#452]
Feedback from chsiang@mozilla.com : Can't find location 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/5844adeba5ebd1010099fde4/de558f06-3584-4872-bcd7-663c40666a5c.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Thu Dec 08 2016 04:31:56 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>65.09888</td></tr><tr><td>Build</td><td>627</td></tr><tr><td>Device type</td><td>iPhone SE</td></tr><tr><td>Device name</td><td>CINDY HSIANG’s iPhone</td></tr><tr><td>Screen size</td><td>320</td></tr><tr><td>Screen size</td><td>320px by 568px</td></tr><tr><td>Battery</td><td>67% Unplugged</td></tr><tr><td>Memory free</td><td>172 MB / 1789 MB</td></tr><tr><td>Disk free</td><td>961 MB / 56506 MB</td></tr><tr><td>Network IP</td><td>172.16.154.133</td></tr></table>

 [Link to buddybuild feedback from build 627](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5848e23c0114d20100f6316d&bnum=627)

**Comment by mcomella** [comment]
#472.
