### ISSUE TITLE
mpopova@mozilla.com on build #655: First card of the series, seems odd considering I am in the…

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#455]
Feedback from mpopova@mozilla.com : First card of the series, seems odd considering I am in the resort

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58489480b7301301006dbd98/5e9380d1-ca11-43c4-a5f7-5f96d2fbc681.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Thu Dec 08 2016 07:51:09 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>16748.52</td></tr><tr><td>Build</td><td>655</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Maria's iPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>96% Unplugged</td></tr><tr><td>Memory free</td><td>56 MB / 1734 MB</td></tr><tr><td>Disk free</td><td>962 MB / 11548 MB</td></tr><tr><td>Network IP</td><td>10.21.19.226</td></tr></table>

 [Link to buddybuild feedback from build 655](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=584910edc37e4f0100cef1d1&bnum=655)

**Comment by mcomella** [comment]
Bad data didn't help this.

Alternative APIs work on the "place attachment" problem and we'll open a new issue if we consider this important enough.
