### ISSUE TITLE
mpopova@mozilla.com on build #655: Walking and driving times are quite off in this latest build

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#456]
Feedback from mpopova@mozilla.com : Walking and driving times are quite off in this latest build

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58489480b7301301006dbd98/20d2a331-d9d0-4144-9a6c-3c061998ac71.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Thu Dec 08 2016 07:53:49 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>16911.47</td></tr><tr><td>Build</td><td>655</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Maria's iPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>96% Unplugged</td></tr><tr><td>Memory free</td><td>32 MB / 1712 MB</td></tr><tr><td>Disk free</td><td>958 MB / 11548 MB</td></tr><tr><td>Network IP</td><td>10.21.19.226</td></tr></table>

 [Link to buddybuild feedback from build 655](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5849118d95b1380100c8d856&bnum=655)

**Comment by mcomella** [comment]
Dupe #443.
