### ISSUE TITLE
mverdi@mozilla.com on build #627: Marble slab is not in this location

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#457]
Feedback from mverdi@mozilla.com : Marble slab is not in this location

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/5844adeba5ebd1010099fde4/edbf35f8-148e-4fd6-9a87-9545483435be.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Thu Dec 08 2016 08:32:19 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>8230.229</td></tr><tr><td>Build</td><td>627</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>VerdiPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>62% Unplugged</td></tr><tr><td>Memory free</td><td>38 MB / 1534 MB</td></tr><tr><td>Disk free</td><td>8172 MB / 56379 MB</td></tr><tr><td>Network IP</td><td>169.254.131.77</td></tr></table>

 [Link to buddybuild feedback from build 627](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=58491a931a0bf80100bc4009&bnum=627)

**Comment by mcomella** [comment]
Bad data from providers - not actionable.
