### ISSUE TITLE
Open Website in browser when tapped in detail screen

### ISSUE THREAD

**Issue by fluffyemily** [mozilla-mobile/prox#46]
When the user taps the URL for the website of the displayed place, the site should be opened in the most appropriate browser.
- If the user has Firefox for iOS installed, the site should be opened in Firefox
- If the user does not have Firefox installed, the site should be opened in Safari

**Comment by fluffyemily** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I want to receive an actionable overview of relevant information about places near me, so that my day is not ruined with FOMO](https://trello.com/c/VPWm03rY/49-i-want-to-receive-an-actionable-overview-of-relevant-information-about-places-near-me-so-that-my-day-is-not-ruined-with-fomo)

**Comment by fluffyemily** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I want to know I'm receiving official information for a given point of interest so that I know it's accurate and reliable](https://trello.com/c/MtTsaUR9/54-i-want-to-know-i-m-receiving-official-information-for-a-given-point-of-interest-so-that-i-know-it-s-accurate-and-reliable)

**Comment by fluffyemily** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user I want to be able to find out more about the place I am looking at so that I can make better decisions about what to do next.](https://trello.com/c/zNEuTpBe/168-as-a-user-i-want-to-be-able-to-find-out-more-about-the-place-i-am-looking-at-so-that-i-can-make-better-decisions-about-what-to-d)

**Comment by mcomella** [comment]
#91 was supposed to fix this but it broke during the demo.

**Comment by mcomella** [comment]
fwiw, this works for me locally – maybe we can close.
