### ISSUE TITLE
v.pomerleau@gmail.com on build #655: Extend the range? Prox is only showing my current location.

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#461]
Feedback from v.pomerleau@gmail.com : Extend the range? Prox is only showing my current location.

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58489480b7301301006dbd98/4b4ea864-fcde-4294-bc98-93e96824088a.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Fri Dec 09 2016 01:45:04 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>68.11877</td></tr><tr><td>Build</td><td>655</td></tr><tr><td>Device type</td><td>iPhone 6</td></tr><tr><td>Device name</td><td>Valerie's iPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>63% Unplugged</td></tr><tr><td>Memory free</td><td>339 MB / 3709 MB</td></tr><tr><td>Disk free</td><td>94839 MB / 116152 MB</td></tr><tr><td>Network IP</td><td>0.0.0.0</td></tr></table>

 [Link to buddybuild feedback from build 655](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=584a0ca08257890100efd39b&bnum=655)

**Comment by brampitoyo** [comment]
This issue is going to be addressed by #158.

**Comment by mcomella** [comment]
Closing in favor of #158.
