### ISSUE TITLE
etoop@mozilla.com on build #661: Feedback for logs

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#463]
Feedback from etoop@mozilla.com : Feedback for logs

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/584a18d061104b0100d0a60f/464397e5-f848-400f-8ae2-92f1335bb610.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Fri Dec 09 2016 03:10:49 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>82.19119</td></tr><tr><td>Build</td><td>661</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Emily's iPhone 6S</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>53% Unplugged</td></tr><tr><td>Memory free</td><td>28 MB / 1777 MB</td></tr><tr><td>Disk free</td><td>14153 MB / 56363 MB</td></tr><tr><td>Network IP</td><td>172.16.151.119</td></tr></table>

 [Link to buddybuild feedback from build 661](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=584a20b9790b2e0100fa5a53&bnum=661)

**Comment by mcomella** [comment]
@fluffyemily Any action items here? Or should we close?

**Comment by fluffyemily** [comment]
Close. I only submitted so I could grab the logs.
