### ISSUE TITLE
etoop@mozilla.com on build #664:

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#464]
Feedback from etoop@mozilla.com : 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/584aeff121d1ce01001c6f89/c8dc5eb8-ac56-4f51-ad26-d29c6075d11f.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Fri Dec 09 2016 19:02:05 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>1624.846</td></tr><tr><td>Build</td><td>664</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Emily's iPhone 6S</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>88% Unplugged</td></tr><tr><td>Memory free</td><td>40 MB / 1812 MB</td></tr><tr><td>Disk free</td><td>13801 MB / 56363 MB</td></tr><tr><td>Network IP</td><td>172.16.151.119</td></tr></table>

 [Link to buddybuild feedback from build 664](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=584affadbce07a0100449348&bnum=664)

**Comment by mcomella** [comment]
@fluffyemily Any action items here? Or should we close?

**Comment by fluffyemily** [comment]
Close. Submitted for logs.
