### ISSUE TITLE
mpopova@mozilla.com on build #671: Excellent suggestions in my new location

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#466]
Feedback from mpopova@mozilla.com : Excellent suggestions in my new location

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/584b702bf9a73301001aae44/41f971ac-17a8-4bf2-a07b-a51e56575445.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Sun Dec 11 2016 19:07:01 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>42668.83</td></tr><tr><td>Build</td><td>671</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>Maria's iPhone</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>80% Unplugged</td></tr><tr><td>Memory free</td><td>51 MB / 1751 MB</td></tr><tr><td>Disk free</td><td>666 MB / 11548 MB</td></tr><tr><td>Network IP</td><td>10.205.253.120</td></tr></table>

 [Link to buddybuild feedback from build 671](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=584da3d52cc56c0100b136c6&bnum=671)

**Comment by mcomella** [comment]
Not actionable.

FYI @antlam
