### ISSUE TITLE
Yelp hours are incorrect for specific location (allow users to flag?)

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#467]
Feedback from porfirio@mozilla.com : Place is actually open... TripAdvisor is wrong. Wouldn't Yelp be a better source for hours? Could we flag incorrect data in the app and let others see it too? --Porfirio

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/584b702bf9a73301001aae44/1b78be94-4063-4203-a233-d81b27f54aa0.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Mon Dec 12 2016 01:53:36 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>359.9941</td></tr><tr><td>Build</td><td>671</td></tr><tr><td>Device type</td><td>iPhone 7 Plus</td></tr><tr><td>Device name</td><td>porfitron’s iPhone</td></tr><tr><td>Screen size</td><td>414</td></tr><tr><td>Screen size</td><td>414px by 736px</td></tr><tr><td>Battery</td><td>47% Unplugged</td></tr><tr><td>Memory free</td><td>189 MB / 2744 MB</td></tr><tr><td>Disk free</td><td>165133 MB / 237056 MB</td></tr><tr><td>Network IP</td><td>0.0.0.0</td></tr></table>

 [Link to buddybuild feedback from build 671](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=584e032069c61f0100e42feb&bnum=671)

**Comment by mcomella** [comment]
> Place is actually open... TripAdvisor is wrong. Wouldn't Yelp be a better source for hours?

We use Yelp for hours – I'm guessing the hours are just wrong for this location.

> Could we flag incorrect data in the app and let others see it too? 

We could consider this.

**Comment by mcomella** [comment]
See https://trello.com/c/ly2QfhMc/135-i-want-to-tell-prox-that-certain-information-being-displayed-is-wrong-so-that-it-can-be-corrected.
