### ISSUE TITLE
Bad UX when app is finding location/downloading places

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#472]
Feedback from chsiang@mozilla.com : Took a long time to not find my location. I closed and left the app as a result of that. 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/584b702bf9a73301001aae44/9c2f9975-29f1-4907-8418-f5be07edab08.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Thu Dec 15 2016 07:07:55 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>57.48987</td></tr><tr><td>Build</td><td>671</td></tr><tr><td>Device type</td><td>iPhone SE</td></tr><tr><td>Device name</td><td>CINDY HSIANG’s iPhone</td></tr><tr><td>Screen size</td><td>320</td></tr><tr><td>Screen size</td><td>320px by 568px</td></tr><tr><td>Battery</td><td>75% Unplugged</td></tr><tr><td>Memory free</td><td>34 MB / 1695 MB</td></tr><tr><td>Disk free</td><td>551 MB / 56506 MB</td></tr><tr><td>Network IP</td><td>10.192.10.85</td></tr></table>

 [Link to buddybuild feedback from build 671](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=5852414b3091ff010078fa10&bnum=671)

**Comment by mcomella** [comment]
See https://trello.com/c/SBJq85xG/354-prox-not-showing-places-even-through-there-are-things-near-me
