### ISSUE TITLE
Determine place database query params (e.g. radius around user) and prioritize results

### ISSUE THREAD

**Issue by fluffyemily** [mozilla-mobile/prox#49]
Taken from renamed trello card. Created by @mcomella

**Comment by fluffyemily** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user I want to see the most useful places when I open the app so that I can make better decisions about my next step](https://trello.com/c/IBEHIXNb/149-as-a-user-i-want-to-see-the-most-useful-places-when-i-open-the-app-so-that-i-can-make-better-decisions-about-my-next-step)

**Comment by mcomella** [comment]
(wrt name change: In order to prioritize the query results, we have to have the right query!)

We have to set default query parameters to get back the results we want (list not exhaustive):
* Radius around the user
* Maximum number of places we'd take (sort by closest?)
* Place categories

Then we need to determine if we'd want to query for places again. For example, an initial query of 1km may leave us with 1 place result, which is not a great user experience. Would we want to make another query with more expansive parameters (e.g. increasing the search radius) to get more results?

After this, we'll need to prioritize the results based on rating, distance, category etc. and show the top few choices to the user.

We should work with UX to tweak the parameters. fwiw, if iterating on the iOS client is slow, it might be worth building a small web app to query the firebase and view the results.

-
@jhugman, afaict front-end progress here is blocked on having a comprehensive list of places around the hotel in Firebase. What would it take to get that working?

**Comment by mcomella** [comment]
@antlam has created some preliminary criteria in [this document under the criteria header](https://docs.google.com/document/d/101jsPjZZ-a_MgZn1UaAyJouufkxzJqG07IrI_0USj1M/edit).

The next steps are to get this into the app to see what UX thinks! See also antlam's comment (via email):

> Next steps would be to see how many places we want to show. That is, how can we establish a reasonable radius criteria? But I imagine that will get easier as we see this on a build/in our UI. And we've left some options to test in the doc too.

**Comment by mcomella** [comment]
I was looking into doing this on the client but I think it's more appropriate to do on the server so we can worry less about the size of our cache. On the server, we'd be filtering by:

1. Rating / review count
1. Categories

@jhugman or @liuche Is this something you could do?

Note that the criteria in the document is correct, including "If (rating = 3) && (review_count > 3) THEN hide". I spoke to antlam on slack:

> the idea is if a places is relatively new, we found that it would have 3 or fewer reviews and the rating of 3 was actually not that bad. As opposed to a place that has 3/5 ratings and has been rated consistently 3/5 by many tohers

-
Once this is complete, we can change the query distance on the client – please let me know when we're ready for this!

**Comment by mcomella** [comment]
Spoke to @liuche on slack: we may have to show places on the client that fall outside of this criteria if they have the events so we can't filter out everything on the server (though we can filter out that criteria, except if it has an event, for example).

I'll implement a client-side solution and the server can determine if they'd like to implement any of this on the server for performance reasons.

**Comment by mcomella** [comment]
@antlam Should the categories in the criteria be whitelisted or blacklisted? e.g. I see that Automotive isn't listed in the document but is on the yelp category list

FYI (to eng): the categories presented in the Places on the client are the child categories, with no reference to the top-level categories, but the document above uses only top-level categories. We'll have to transform child categories into the top-level categories somehow, either in advance on the server or in real time on the client.

**Comment by antlam** [comment]
I don't have a preference for Kona. Is this an important decision to decide on right now?

**Comment by antlam** [comment]
As for Automotive missing, that must have been by accident. Sorry!

Adding it back now as a "hide"

**Comment by mcomella** [comment]
> I don't have a preference for Kona.

Ultimately, I think we'd prefer a whitelist – only categories we specifically said to show will appear, preventing any surprises.

For determining the criteria, you'd probably prefer blacklisting – anything you've said to hide will be hidden and everything else will be shown.

**However**, I realized places can have multiple categories making this question a little more complicated. Of these options, which do we want to do:
1. (most permissive) Hide places that have at least 1 category we said to hide
1. Hide places whose categories (all of them) we said to hide
1. Show places that match at least 1 category we said to show
1. (least permissive) Show places whose categories (all of them) we said to show

Or some other combination?

fwiw, the first two are blacklisting and the last two are whitelisting.

-
> Is this an important decision to decide on right now? 

Before Hawaii, yes – we either have to blacklist or whitelist the categories to determine which ones to show, but it's (relatively) easy to overturn later.

**Comment by antlam** [comment]
@mcomella 

> However, I realized places can have multiple categories making this question a little more complicated. Of the following options, which do we want to do?
> 
> 1. (most permissive) Hide places that have at least 1 category we said to hide
> 2. Hide places whose categories (all of them) we said to hide
> 3. Show places that match at least 1 category we said to show
> 4. (least permissive) Show places whose categories (all of them) we said to show

Since anything we do here will require some element of curation, **I think we should go with 1** for now. Then we can do an additional round of curation after we see what results we get back.

**Comment by mcomella** [comment]
^ Filed some followups.
