### ISSUE TITLE
Integrate App Analytics

### ISSUE THREAD

**Issue by fluffyemily** [mozilla-mobile/prox#50]
Sounds like we need to use Optimizely. See trello card for details.

**Comment by fluffyemily** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a product manager I want to be able to see how users are using the app and where they are spending their time so that I can make better product decisions](https://trello.com/c/g24DbH7X/161-as-a-product-manager-i-want-to-be-able-to-see-how-users-are-using-the-app-and-where-they-are-spending-their-time-so-that-i-can-m)

**Comment by liuche** [comment]
Fixed in Pull #256
