### ISSUE TITLE
Refine groups for filtering

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/prox#511]
Not sure if we filed this anywhere but here's the category grouping we want to start using based on what we get back from Yelp right now.

**Discover**
- Active Life
- Arts & Entertainment
- Local Flavor
- Hotels & Travel
- Landmarks & Historical Buildings **(Sub-category under Public Services & Government)**

**Eat & Drink**
- Food
- Nightlife
- Restaurants

**Shop**
- Shopping

**Services**
- Automotive
- Beauty & Spas
- Bicycles
- Education
- Event Planning & Services 
- Financial Services
- Health & Medical
- Home Services
- Local Services
- Professional Services
- Mass Media
- Pets
- Public Services & Government 
- Real Estate
- Religious Organizations

**Comment by mariapopova0729** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I want to be able to surface different types of places so that I can always get the most relevant information to me](https://trello.com/c/csJcpiPQ/364-i-want-to-be-able-to-surface-different-types-of-places-so-that-i-can-always-get-the-most-relevant-information-to-me)

**Comment by thebnich** [comment]
@antlam any reason "Landmarks & Historical Buildings" is under "Services" rather than "Discover"?

**Comment by antlam** [comment]
huh, that must've been a mistake. 

Good catch!

**Comment by antlam** [comment]
@thebnich actually, we only looked at this level of the categories and Yelp puts them under "Public Services & Government".

Since Yelp things can be in multiple categories, we decided to leave it and see what we would get.

But we could special case this sub-category and pull them out into Discover...  we should monitor this closely though because it could get weird.

**Comment by thebnich** [comment]
Since "Landmarks & Historical Buildings" isn't a top-level item, this is a bit tricky. For now, I'll keep this under services, but we should update our top-level-category-finding algorithm to stop on certain sub-categories (like this one).

**Comment by thebnich** [comment]
We landed most of these groups in the filtering PR, but I'll keep this open since there's still some tweaking to do (e.g., Landmarks as mentioned above).

**Comment by thebnich** [comment]
Fixed by #555.
