### ISSUE TITLE
Clicking map button freezes app

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/prox#518]

**Comment by mcomella** [comment]
I briefly looked into this – if you change `PlaceDetailViewController.close` to `self.dismiss(animated: false)`, a white screen will appear rather than the app freezing. I opened the UI hierarchy debugger and it appears that the white screen doesn't appear at all:
<img width="495" alt="screen shot 2017-02-13 at 13 27 15" src="https://cloud.githubusercontent.com/assets/759372/22904160/34dd04b0-f1f0-11e6-8c8f-84f5b9e5fde5.png">

Due to how the animation change affects this issue, I think this may be an animation issue.

If not, I think this may have happened after Brian updated to the new schema, which was missing place information – perhaps the missing information is the cause? (e.g. we silently fail with the missing data?)

Anyway, this isn't super important because we're likely removing this view so I'll go work on something else.

**Comment by mcomella** [comment]
There is also this ambiguous layout issue:
<img width="1125" alt="screen shot 2017-02-13 at 13 30 06" src="https://cloud.githubusercontent.com/assets/759372/22904257/9d0ca892-f1f0-11e6-90d4-b22613331f87.png">

**Comment by thebnich** [comment]
Fixed by #523.
