### ISSUE TITLE
Add error state when no places match filters

### ISSUE THREAD

**Issue by thebnich** [mozilla-mobile/prox#522]
If the user opens the filter view and deselects all filters (or selects only filters that have no places), we should show some UI telling them that there are no matches.

**Comment by antlam** [comment]
Just so I remember...

This is when we hide the card underneath the overlay, and disable the "x" so the user has to reselect one of the filters.

**Comment by antlam** [comment]
Here's a visual of what we're talking about so far 
<img width="420" alt="screen shot 2017-02-25 at 2 17 19 pm" src="https://cloud.githubusercontent.com/assets/1994820/23335222/30f48da4-fb65-11e6-9fa6-fbe8db5b083c.png">
