### ISSUE TITLE
Improve filtering animation

### ISSUE THREAD

**Issue by thebnich** [mozilla-mobile/prox#526]
Right now, the filter UI just overlays the top of the card. The mockups show an animation that pushes the card down, so we should implement that.

**Comment by antlam** [comment]
From @brampitoyo 

> (Though the animation is up to date, the visual design isn’t. Follow the one outlined by @antlam up above).

![a4266c5e-f375-11e6-87c0-c734e9f46c1b](https://cloud.githubusercontent.com/assets/1994820/23049961/4f568e02-f474-11e6-896c-ce80bcb473ac.gif)
