### ISSUE TITLE
Set Default filters for new users

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/prox#532]
With the new filters capability, setting a sensible default is a deliberate choice we'll have to make.

Based on what we've heard from our research and the problems we're trying to address, I'd suggest we use the following:

![iphone 7 - home - filters](https://cloud.githubusercontent.com/assets/1994820/23050245/f2ee06f2-f475-11e6-8444-a5d01a8c8ffb.png)

Of course, we should measure how this performs too and be ready to change it in the future. Thoughts?

**Comment by thebnich** [comment]
Done.
