### ISSUE TITLE
Remove line below map view categories; adjust spacing

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/prox#54]
I'm using, e.g. `Beach | Hotel | Whatever`, as a placeholder.

@antlam for proper designs.

**Comment by mcomella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Polish displaying multiple categories on place carousel](https://trello.com/c/NblRfE5m/173-polish-displaying-multiple-categories-on-place-carousel)

**Comment by mcomella** [comment]
@antlam Please also consider what happens when the text overflows the bounds of the view.

**Comment by antlam** [comment]
- 12px padding between each category
- 3 category max (for now)
- same 12px (1px thick) divider underneath (centered, 4px padding from bottom of category text)

![screen shot 2016-10-25 at 2 50 09 pm](https://cloud.githubusercontent.com/assets/1994820/19705705/cbe737fc-9ac2-11e6-98af-856dcbc98df3.png)

**Comment by mcomella** [comment]
@antlam This sounds hard because we have to dynamically set underlines to different category text and the edge cases need working out (what happens when the text overflows)?

How do you feel about the current design?

![screen shot 2016-11-04 at 15 04 19](https://cloud.githubusercontent.com/assets/759372/20023880/1824dd92-a2a0-11e6-82ac-8244d2d29e59.png)

**Comment by antlam** [comment]
We can remove the underline for the time being. But we should also be capping the maximum at 3 categories.

Is this the same styling as the Home View categories label? @mcomella

**Comment by mcomella** [comment]
> We can remove the underline for the time being.

Remove the underline altogether? If so, should the category text move down to compensate?

> But we should also be capping the maximum at 3 categories.

Done but note that we ellipse if we overflow.

> Is this the same styling as the Home View categories label?

Should be!
![simulator screen shot nov 4 2016 15 11 27](https://cloud.githubusercontent.com/assets/759372/20024054/24771fb4-a2a1-11e6-9270-b275fde2b5d6.png)

**Comment by antlam** [comment]
![spec_map_categories](https://cloud.githubusercontent.com/assets/1994820/20024143/03757d82-a2a2-11e6-9f09-faa4ea34c302.png)

@mcomella attached updated spec

**Comment by mcomella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user, I want the app to match the UX as designed](https://trello.com/c/vNffsUzV/202-as-a-user-i-want-the-app-to-match-the-ux-as-designed)

**Comment by mcomella** [comment]
To be explicit, we should remove the line underneath the category list in the map view and adjust to the spacing in the spec above.

**Comment by antlam** [comment]
We'll likely be working on a new "Map/Alternative view" that will change the UI/UX here. Closing for now.
