### ISSUE TITLE
Custom icon for Map View markers

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/prox#547]
Over to @antlam for designs.

**Comment by antlam** [comment]
[iconsformap.zip](https://github.com/mozilla-mobile/prox/files/832417/iconsformap.zip)
![icon_map_inactive2](https://cloud.githubusercontent.com/assets/1994820/23773147/c7bba12a-04d2-11e7-94cd-a3a428362edf.png)
![icon_map_active](https://cloud.githubusercontent.com/assets/1994820/23773150/c951f34a-04d2-11e7-9b03-728c7803afd2.png)

**Comment by antlam** [comment]
[iconsformap2.zip](https://github.com/mozilla-mobile/prox/files/832488/iconsformap2.zip)

Fixed the assets!
