### ISSUE TITLE
Use Branded UI for Ratings

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/prox#558]

**Comment by antlam** [comment]
To be clear, this is just about the stars and circles.

**Comment by mcomella** [comment]
@antlam What's the vertical spacing between the yelp logo <- stars -> review count?

**Comment by antlam** [comment]
<img width="342" alt="screen shot 2017-03-01 at 9 41 54 pm" src="https://cloud.githubusercontent.com/assets/1994820/23494475/ecc5d0be-fec7-11e6-85b6-09f0a8a1cb21.png">

4px between the logo asset + ratings asset, and 4px between the ratings assets + "# Reviews"

**Comment by mcomella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I want Prox to show me the familiar ratings from providers like Yelp and TA (incorporate Branded UI)](https://trello.com/c/HH0hLtSM/372-i-want-prox-to-show-me-the-familiar-ratings-from-providers-like-yelp-and-ta-incorporate-branded-ui)
