### ISSUE TITLE
buddybuild feedback on build #785: Icons are squished in Filters UI

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#567]
Feedback: Icons are squished in Filters UI

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/58b4b77297ac7e01005b74e0/a45f290a-045f-467b-b000-c4b3b9e3f772.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Tue Feb 28 2017 00:11:05 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>186.2817</td></tr><tr><td>Build</td><td>785</td></tr><tr><td>Device type</td><td>iPhone 7</td></tr><tr><td>Device name</td><td></td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>53% Unplugged</td></tr><tr><td>Memory free</td><td>54 MB / 1814 MB</td></tr><tr><td>Memory free</td><td>54768 MB / 116232 MB</td></tr><tr><td>Network IP</td><td>0.0.0.0</td></tr></table>

**Comment by mcomella** [comment]
@thebnich FYI.
