### ISSUE TITLE
Add custom (event) description collapsable menu item

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/prox#571]
For events, we may want to add custom descriptions (like the Yelp top line).

@antlam if this is something we want, what icon and copy should we use for this view?

@bram CC

**Comment by brampitoyo** [comment]
I looked at how event sites – Eventbrite, Eventful, AllEvents.in, Gumtree, SpinGo (full list: http://blog.evvnt.com/where/) describe their listings, and would suggest two heading alternatives based on everything I saw:

1. Event Details
2. Description

Alternatively, some sites show the description outright without a heading at all. It’s more consistent for us to use a heading, though, so we should do that.

And I don’t think we need any icon to represent this section.

What do you think, @antlam?

**Comment by antlam** [comment]
I dont think we need this for Chicago but we can revisit this later.

Closing for now.

**Comment by mcomella** [comment]
Anthony said we needed this. :)

**Comment by antlam** [comment]
Brian pinged me for Assets and copy.

I suggested no image asset for the time being and just going with "Event details".

Given that there isn't an image, can we just left align the text to the same edge as the place card name?
