### ISSUE TITLE
Remove Services from the filter UI

### ISSUE THREAD

**Issue by thebnich** [mozilla-mobile/prox#592]
We've kept Services in the filter UI as a way to see what we were missing from the other categories, but the plan is to remove Services before Chicago.

Also, we removed the badge count from the map view because this allows us to add as many places as we want without feeling overwhelmed there are "too many". I think we decided to remove the count from the filter UI for the same reasons.

**Comment by liuche** [comment]
Talked to antlam to clarify, and he said to leave the place count in for the Chicago build, and discuss later.
