### ISSUE TITLE
Clean up transitions when swiping between place details images

### ISSUE THREAD

**Issue by vazquez** [mozilla-mobile/prox#60]
Now that we are removing background map from the Home View, we are thinking of new interactions involving the background image.

**Comment by vazquez** [comment]
![2016-10-27 15_44_03](https://cloud.githubusercontent.com/assets/1119821/19782580/6a380dba-9c5c-11e6-8494-4b88058ec468.gif)

**Comment by vazquez** [comment]
This is for the most part working. If we could get a transition between background, similar to a cross-fade, this issue can be closed.

**Comment by fluffyemily** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Polish: Add Animation where required](https://trello.com/c/IO2uMqgG/107-polish-add-animation-where-required)

**Comment by sleroux** [comment]
https://github.com/mozilla-mobile/prox/pull/293
