### ISSUE TITLE
Resolve behavior of "Sort by popularity" & Discover

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/prox#620]

**Comment by thebnich** [comment]
Sounds like we're going with a toast at the bottom of the screen when the user turns the toggle on. The toast will tell the user that the toggle works better when non-Discover filters are enabled.

Waiting on @antlam for the copy.

**Comment by antlam** [comment]
when the user first turns on the toggle...

"Select more filters to get better results"
