### ISSUE TITLE
Scrolling Crash

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/prox#644]
i managed to get prox in a state where the active card is stuck. the app didn't crash until i clicked the filter button on the top left.

![image](https://cloud.githubusercontent.com/assets/4879954/24065415/05b9ad7c-0b28-11e7-8a8c-93390b538b31.png)

[Here](https://mozilla.slack.com/files/sdaswani/F4KFS47DE/prox__3-17-17__3-28_pm_crash.crash) is the crash report, this is the SF location build I was sent earlier, so hopefully it can be easily symbolicated.

The symbolicated crash can be found here: https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/crashreport/b8292072a18ac7838eeca8609b8c20ab

**Comment by mcomella** [comment]
Dupe #492. The crash report could be useful – thanks for filing! :)
