### ISSUE TITLE
apikeys.plist

### ISSUE THREAD

**Issue by duchu** [mozilla-mobile/prox#655]
How should look plist file with api keys ? 
I was trying to find it on firebase but no luck.

**Comment by kbrosnan** [comment]
You would need to acquire your own api keys for the services. The keys are not sharable, see https://www.yelp.com/developers/api_terms section 3 and https://developer-tripadvisor.com/content-api/terms-and-conditions/ section 4.

**Comment by mcomella** [comment]
Hey @duchu – is there something specific you're trying to do? Maybe there's some way we can help shortcut the amount of effort it'd take you. We don't have many new developers and so we haven't invested in making it easy to set up the project.

If you were hoping to contribute code, we're currently considering new product directions so changing the current code is probably not worthwhile. If you're interested in future opportunities, please let me know and we'll try to find a role for you. To set expectations, this is a lightweight, experimental project so we won't be able to provide as much assistance as other projects and you'll be expected to complete your tasks quickly.
