### ISSUE TITLE
Allow for scrolling between places in detail view

### ISSUE THREAD

**Issue by fluffyemily** [mozilla-mobile/prox#68]
Users are required to be able to scroll between places when in the detail view without having to return to the overview carousel

**Comment by fluffyemily** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I want to receive an actionable overview of relevant information about places near me, so that my day is not ruined with FOMO](https://trello.com/c/VPWm03rY/49-i-want-to-receive-an-actionable-overview-of-relevant-information-about-places-near-me-so-that-my-day-is-not-ruined-with-fomo)

**Comment by antlam** [comment]
Specs in Issue 11 here https://cloud.githubusercontent.com/assets/1119821/19779509/6a057812-9c4f-11e6-8e3f-c99c8f59802a.png :)

**Comment by mcomella** [comment]
Closed by #68.
