### ISSUE TITLE
sarentz@mozilla.com on build #130: Prox starts like in this screenshot and stays there for a…

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/prox#69]
Feedback from sarentz@mozilla.com : Prox starts like in this screenshot and stays there for a really long time. Like 30 seconds. After that it switches to the card view. 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/57f51f8bcaa70a01005412ee/581344efe76efc0100b136aa/a553a1fc-a9ef-46f5-825c-dfdd2fcad93b.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Mon Oct 31 2016 12:32:15 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>63.50494</td></tr><tr><td>Build</td><td>130</td></tr><tr><td>Device type</td><td>iPhone 6s Plus</td></tr><tr><td>Device name</td><td>Stefan's iPhone 6s Plus</td></tr><tr><td>Screen size</td><td>414</td></tr><tr><td>Screen size</td><td>414px by 736px</td></tr><tr><td>Battery</td><td>91% Unplugged</td></tr><tr><td>Memory free</td><td>43 MB / 1687 MB</td></tr><tr><td>Disk free</td><td>15778 MB / 116073 MB</td></tr><tr><td>Network IP</td><td>0.0.0.0</td></tr></table>

 [Link to buddybuild feedback from build 130](https://dashboard.buddybuild.com/apps/57f51f8bcaa70a01005412ee/feedback?fid=581739cf97ebe70100ea25ca&bnum=130)

**Comment by mcomella** [comment]
I notice this in my local builds.

My log statement, "lol geofire query has completed" is called when the view changes so we might be blocking the UI update on the geofire query.

**Comment by sarentz** [comment]
The UI thread is not completely blocked BTW. I do see the location
indicator on the map pulse in and out.

**Comment by mcomella** [comment]
@fluffyemily Why was this closed? My simulator builds sometimes hang in this screen so I assume it'd happen on device too.

**Comment by fluffyemily** [comment]
I closed it because it was asymptom of a lack of a loading screen and not a
'bug' as such. I thought I had linked to the loading screen issue in it
when I closed it but maybe I forgot

**Comment by fluffyemily** [comment]
This is fundamentally a symptom of the length of time it takes to find a location sometimes. This has been partially addressed by the removal of the map, but it still takes time to discover a location and find some places.

Handling this is addressed with the `loading screen` as specified in #131 which will show that we are doing something without make it feel like the app is hanging.
