### ISSUE TITLE
Implement forward-arrow on Summary Card

### ISSUE THREAD

**Issue by vazquez** [mozilla-mobile/prox#84]
We received feedback from the User Testing round that people did not know where to tap to receive walking (or driving) directions. As such, we are modifying the design just a bit.

We are using the iOS' `arrow-forward` icon. Exported assets can be found here: https://www.dropbox.com/sh/b30k7wfqerbbb7f/AACdQhl1QKr0MnQyly6KGngSa?dl=0

`icon_forwardarrow.png`
`icon_forwardarrow@2x.png`
`icon_forwardarrow@3x.png`

![screenshot 2016-11-03 15 22 34](https://cloud.githubusercontent.com/assets/1119821/19981701/5fa4b240-a1d9-11e6-844d-ca523f39cc75.png)

![screenshot 2016-11-03 15 22 19](https://cloud.githubusercontent.com/assets/1119821/19981700/5fa2ea0a-a1d9-11e6-8beb-87aaf769d786.png)

**Comment by mcomella** [comment]
I see no forward arrow asset but I can try drawing it in code.

**Comment by mcomella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user, I want improvements discovered in user testing implemented in my app](https://trello.com/c/yBpRsKZL/200-as-a-user-i-want-improvements-discovered-in-user-testing-implemented-in-my-app)

**Comment by vazquez** [comment]
@mcomella I have the icon!

`icon_forward.png`
`icon_forward@2x.png`
`icon_forward@3x.png`

https://www.dropbox.com/sh/b30k7wfqerbbb7f/AACdQhl1QKr0MnQyly6KGngSa?dl=0

**Comment by mcomella** [comment]
@vazquez In the mock, is the arrow supposed to be 24px? The asset is only 16px high and the size guide expands the size of the image so I wasn't sure. Here it is at its native size:

![simulator screen shot nov 9 2016 16 59 23](https://cloud.githubusercontent.com/assets/759372/20160706/e0e518ae-a69d-11e6-85ef-d1ce4c4ab327.png)

**Comment by vazquez** [comment]
@mcomella – What a designer eye you have!

The spec was off, my apologies. The 16px size is good to go 👍
