### ISSUE TITLE
"Current Location" UI When User is at Location

### ISSUE THREAD

**Issue by vazquez** [mozilla-mobile/prox#85]
When the user is in the venue's location, we don't need to show the Location UI. For these cases, we need to hide the "Current Location" UI and show a "You're here!" Badge.

**Comment by antlam** [comment]
![home - current](https://cloud.githubusercontent.com/assets/1994820/19989551/8b484a0a-a1e4-11e6-83a4-a9e6534cc888.png)

**Comment by antlam** [comment]
"You're here!" is centered, in the same style as "Until closing" and the icon is padded 9px, same as the other icons (next to closing times)

**Comment by mcomella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user, I want improvements discovered in user testing implemented in my app](https://trello.com/c/yBpRsKZL/200-as-a-user-i-want-improvements-discovered-in-user-testing-implemented-in-my-app)
