### ISSUE TITLE
New Background Image on Map View

### ISSUE THREAD

**Issue by vazquez** [mozilla-mobile/prox#88]
We received feedback from User Testing indicating that people felt that the map background was actionable. To avoid people thinking the map is actionable, we have decided to put a different3- blur map on map view to make it obvious users can’t interact with map.

## Design

![map copy 3](https://cloud.githubusercontent.com/assets/1119821/20006738/55ecb4e6-a26f-11e6-8cc8-aa10530051da.png)

## Specs

![map specs](https://cloud.githubusercontent.com/assets/1119821/20007120/33d6d90c-a271-11e6-8da0-b237fdc4b6a0.png)

## Images

Images are available on the Dropbox Folder: https://www.dropbox.com/sh/b30k7wfqerbbb7f/AACdQhl1QKr0MnQyly6KGngSa?dl=0

`map_background.png`
`map_background@2x.png`
`map_background@3x.png`

**Comment by mcomella** [comment]
Fixed in #91 but see follow-up #103.

**Comment by vazquez** [comment]
Reopening this issue, as the fading is not appearing in the Prox Build. New images GH issue is in #103

**Comment by mcomella** [comment]
Should be fixed in latest:
![simulator screen shot nov 8 2016 13 23 14](https://cloud.githubusercontent.com/assets/759372/20117693/86f2a952-a5b6-11e6-8b17-9b4a3c793204.png)
