### ISSUE TITLE
Implement Event Badge UI

### ISSUE THREAD

**Issue by vazquez** [mozilla-mobile/prox#99]
Whenever we send a push notification to a user, we will show them a special card which will contain a badge UI with relevant information to the event.

**Comment by antlam** [comment]
![screen shot 2016-11-04 at 2 04 51 pm](https://cloud.githubusercontent.com/assets/1994820/20022424/bebf83d6-a297-11e6-8761-b3d488e4a1fc.png)

**Comment by antlam** [comment]
![spec_iconevent_padding](https://cloud.githubusercontent.com/assets/1994820/20022595/78a70efe-a298-11e6-8394-1383d81f4848.png)
![spec_event_padding](https://cloud.githubusercontent.com/assets/1994820/20022594/78a2e59a-a298-11e6-8c6d-a111a284aaec.png)
![spec_event_type](https://cloud.githubusercontent.com/assets/1994820/20022596/78a870dc-a298-11e6-8c91-054ddc361701.png)

**Comment by liuche** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Event badging to the card for events.](https://trello.com/c/bDfP6HSD/196-add-event-badging-to-the-card-for-events)

**Comment by liuche** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I want my Prox cards to also include events that will be happening soon because this might make me more interested in visiting the venues.](https://trello.com/c/Zf5kaT3F/195-i-want-my-prox-cards-to-also-include-events-that-will-be-happening-soon-because-this-might-make-me-more-interested-in-visiting-t)

**Comment by liuche** [comment]
@vazquez Question, will the string used in the notification be the same one as the one displayed in the badge? (assuming the "More info" is badge-only)

**Comment by antlam** [comment]
@liuche is this related to what Mcomella pinged about in Slack yesterday? If so, we still aren't sure about the copy yet. Could they be independent?

**Comment by vazquez** [comment]
+1 for the possibility of them being independent

**Comment by mcomella** [comment]
Note: I'm tracking the sub-problems of this issue on the trello card.
